# -*- coding: utf-8 -*-
# Batch 5 content (part 1): opinion complete + question wave 1.
ARCS = [
{
 "arcId": "ufo_producers_compromised",
 "legitimacy": "Questionable",
 "gender": "male",
 "personality": "cold_factual",
 "summary": "Caller argues the show's screeners filter for belief and bury dry skeptics in the second hour",
 "notes": "Meta opinion caller - conspiracy about the show itself. Vern answers with total transparency: how screening actually works, the caller is on the air as counter-evidence, and invites him to keep calling with details",
 "turns": [
  ("v", {
   "neutral": "You're on the air. You called about this show's screening process - not the lights. Go ahead.",
   "tired": "... you're on. you called about the screening process. not the lights. go ahead.",
   "irritated": "You're on. You've called about my screening process, not the lights. Go.",
   "gruff": "You're on. The screening process. Go.",
   "amused": "You're on the air to critique the screening process! A man after my own heart - go ahead.",
   "focused": "You're on the air. Your subject is this program's caller screening. Proceed.",
  }),
  ("c",
   "I've listened for years, and your screening is the story. Watch who gets on the air: always emotional, always believing, never once a dry voice saying it was a balloon. Your screeners filter for belief - consciously or not - and your ratings depend on it.",
   "I've listened for years, and your screening is the story, Vern. Watch who gets on the air: always emotional, always believing, never once a dry voice saying it was a balloon. Your screeners filter for belief - consciously or not - and your, uh... your ratings depend on it."),
  ("v", {
   "neutral": "That's an interesting theory. What does it say about the caller on the line right now - you? What did my screener ask you - belief, or dates?",
   "tired": "... interesting theory. what does it say about the caller on the line right now - you? what did my screener ask you - belief, or dates?",
   "irritated": "Interesting theory. What does it say about the caller on the line right now - you? What did my screener ask - belief, or dates?",
   "gruff": "Interesting theory. What does it say about you being on right now? Screener ask your belief, or your dates?",
   "amused": "Ha - interesting theory! What does it say about the caller on the line right now - YOU? What did my screener ask you - belief, or dates?",
   "focused": "Compelling theory. Test it against the present case: you are on the air. What did screening request of you - belief statements, or temporal data?",
  }),
  ("c",
   "She asked what I do for a living, when I started listening, and whether I'd seen anything. Then she told me opinion calls go on in the second hour. So you do sort us - belief gets prime time, opinion gets leftovers. That's the filter, and you just confirmed it.",
   "She asked what I do for a living, when I started listening, and whether I'd seen anything. Then she told me opinion calls go on in the second hour, man. So you do sort us - belief gets prime time, opinion gets leftovers. That's the filter, and you just, uh... you just confirmed it."),
  ("v", {
   "neutral": "That's a lineup, not a filter - and here's how the sausage actually gets made, since you're asking. We take maybe four calls an hour. The screener's job isn't belief, it's clarity: can you say what happened, when it happened, and where you stood. I've cut believers off mid-sentence and I've run a skeptic past the sign-off. The sorting you're describing has a name in this business - it's called a show. Every hour picks the calls that make good radio. Including yours.",
   "tired": "... that's a lineup, not a filter. here's how the sausage gets made, since you're asking: we take maybe four calls an hour. the screener's job isn't belief, it's clarity - can you say what happened, when, and where you stood. i've cut believers off mid-sentence and run a skeptic past sign-off. the sorting you describe has a name in this business... it's called a show. every hour picks the calls that make good radio. including yours.",
   "irritated": "That's a lineup, not a filter - and here's how the sausage actually gets made, since you're asking. We take maybe four calls an hour. The screener's job isn't belief, it's clarity: can you say what happened, when it happened, and where you stood. I've cut believers off mid-sentence and run a skeptic past sign-off. The sorting you're describing has a name in this business - it's called a show. Every hour picks the calls that make good radio. Including yours.",
   "gruff": "Lineup, not a filter. Sausage, since you're asking: four calls an hour, maybe. Screener's job isn't belief - clarity. What happened, when, where you stood. Cut believers mid-sentence. Run skeptics past sign-off. The sorting's got a name: a show. Every hour picks calls that make good radio. Including yours.",
   "amused": "That's a LINEUP, not a filter - and here's how the sausage actually gets made, since you're asking! We take maybe four calls an hour! The screener's job isn't belief, it's clarity: can you say what happened, when it happened, and where you stood! I've cut believers off mid-sentence and I've run a skeptic past the sign-off! The sorting you're describing has a name in this business - it's called a SHOW! Every hour picks the calls that make good radio - including yours!",
   "focused": "That describes sequencing, not filtration. Operational detail: approximately four calls per hour reach air. Screening evaluates narrative clarity - event, timestamp, observer position - not belief content. Believers have been terminated mid-broadcast; skeptics have run past sign-off. The pattern you identify is standard programming: hourly selection optimizing broadcast quality. Your call was selected under identical criteria.",
  }),
  ("c",
   "The calls that make good radio... you're admitting selection exists, then.",
   "The calls that make good radio... you're admitting selection exists, then, Vern."),
  ("v", {
   "neutral": "I'm admitting selection exists in every broadcast since Marconi - and that it beats the alternative, which is dead air. Here's the difference between me and the room you're worried about: I'll tell you how the sausage gets made, on the air, while you're eating it. The screener asks occupation, dates, directions. She never asks belief. You're on the line - that's not a filter, that's a Tuesday. Keep calling. The second hour is your hour.",
   "tired": "... selection exists in every broadcast since marconi - and it beats the alternative, which is dead air. the difference between me and the room you're worried about: i'll tell you how the sausage gets made, on the air, while you're eating it. screener asks occupation, dates, directions. never belief. you're on the line - that's not a filter, that's a tuesday. keep calling... the second hour's your hour.",
   "irritated": "I'm admitting selection exists in every broadcast since Marconi - and that it beats the alternative, which is dead air. The difference between me and the room you're worried about: I'll tell you how the sausage gets made, on the air, while you're eating it. The screener asks occupation, dates, directions. She never asks belief. You're on the line - that's not a filter, that's a Tuesday. Keep calling. The second hour is your hour.",
   "gruff": "Selection exists in every broadcast since Marconi - beats the alternative, which is dead air. Difference between me and your imagined room: I tell you how the sausage gets made, on air, while you eat it. Screener asks occupation, dates, directions. Never belief. You're on the line - not a filter, a Tuesday. Keep calling. Second hour's yours.",
   "amused": "I'm admitting selection exists in every broadcast since MARCONI - and that it beats the alternative, which is dead air! Here's the difference between me and the room you're worried about: I'll tell you how the sausage gets made, on the air, while you're eating it! The screener asks occupation, dates, directions - she never asks belief! You're on the line - that's not a filter, that's a Tuesday! Keep calling, my friend - the second hour is YOUR hour!",
   "focused": "Selection is inherent to broadcasting since Marconi, and preferable to dead air. My distinction from the apparatus you posit: full operational transparency, delivered live. Screening collects occupation, dates, bearings - belief is never solicited. Your presence on the line falsifies the filter hypothesis. Continue calling; the second-hour slot remains available to you.",
  }),
  ("c",
   "The second hour is my hour... alright. That's the most honest answer I've ever gotten from a radio station. I'll keep calling.",
   "The second hour is my hour... alright. That's the most honest answer I've ever gotten from a radio station, man. I'll keep calling, you know that."),
  ("v", {
   "neutral": "Keep calling - and next time, bring me the balloon. Your balloon, with its date, its bearing, and your occupation attached, because here's the secret of this show: the boring ones are welcome too. It's not the believing that gets you on the air. It's the details. Thanks for calling.",
   "tired": "... keep calling. and next time, bring me the balloon. your balloon, with its date, its bearing, and your occupation attached - here's the secret of this show: the boring ones are welcome too. it's not the believing that gets you on the air... it's the details.",
   "irritated": "Keep calling - and next time, bring me the balloon. Your balloon, with its date, its bearing, and your occupation attached. Here's the secret of this show: the boring ones are welcome too. It's not the believing that gets you on the air. It's the details. Thanks for calling.",
   "gruff": "Keep calling. Next time bring the balloon - date, bearing, occupation attached. Secret of this show: boring ones welcome too. Not the believing gets you on air. The details.",
   "amused": "Keep calling! And next time, bring me the balloon - YOUR balloon, with its date, its bearing, and your occupation attached! Because here's the secret of this show: the boring ones are welcome too! It's not the believing that gets you on the air, my friend - it's the details! Thanks for calling!",
   "focused": "Continue calling. Next submission: your balloon case with date, bearing, and occupation documented. This program's operating principle: mundane cases are admissible. Air access correlates with detail quality, not belief. Thank you for calling.",
  }),
 ],
},
{
 "arcId": "ufo_sleep_paralysis_purist",
 "legitimacy": "Fake",
 "gender": "male",
 "personality": "cold_factual",
 "summary": "Grad student insists every abduction report is sleep paralysis - no exceptions",
 "notes": "Opinion caller with real knowledge of the sleep literature but an unfalsifiable position (Fake). Vern concedes every bedside case, then holds the highway line: paralysis is a solo act - it can't move cars or fuel. Offers the two-car file as a challenge",
 "turns": [
  ("v", {
   "neutral": "You're on the air. You told the screener you can explain every abduction report ever filed with one diagnosis. Go ahead.",
   "tired": "... you're on. one diagnosis for every abduction report ever filed. go ahead.",
   "irritated": "You're on. One diagnosis for every abduction report. Go.",
   "gruff": "You're on. The one diagnosis. Go.",
   "amused": "You're on the air with one diagnosis for every abduction report ever filed! Bold! Go ahead.",
   "focused": "You're on the air. You propose a single diagnostic explanation for all abduction reports. Proceed.",
  }),
  ("c",
   "Sleep paralysis. All of it. REM intrusion, hypnagogic hallucination, presence in the room - the literature is settled. Your abductees aren't lying, they're having a medical event that's been documented since before the word alien existed. The old hag, the incubus, the night visitor - same paralysis, different century's wardrobe.",
   "Sleep paralysis. All of it. REM intrusion, hypnagogic hallucination, presence in the room - the literature is settled, Vern. Your abductees aren't lying, they're having a medical event that's been documented since before the word alien existed. The old hag, the incubus, the night visitor - same paralysis, different century's wardrobe, man."),
  ("v", {
   "neutral": "That's a genuinely educated answer, and half of it is right. So tell me - what does your theory do with the cases that don't happen in bed?",
   "tired": "... genuinely educated answer, and half of it's right. so tell me - what does your theory do with the cases that don't happen in bed?",
   "irritated": "Genuinely educated answer - and half of it is right. What does your theory do with the cases that don't happen in bed?",
   "gruff": "Educated answer. Half right. What does your theory do with cases that don't happen in bed?",
   "amused": "Ha - that's a genuinely educated answer, and half of it is RIGHT! So tell me: what does your theory do with the cases that don't happen in bed?",
   "focused": "An educated hypothesis - substantially correct for bedside cases. Address the remainder: what does your model predict for events occurring outside the bedroom?",
  }),
  ("c",
   "There is no bed, there is no case. Every abduction starts in a bedroom. The highway stories are confabulation layered on top - memory reconstruction under hypnosis, suggestible subjects, therapists feeding the script. The literature covers that too.",
   "There is no bed, there is no case. Every abduction starts in a bedroom, Vern. The highway stories are confabulation layered on top - memory reconstruction under hypnosis, suggestible subjects, therapists feeding the script, man. The literature covers that too."),
  ("v", {
   "neutral": "The literature covers it - and it also covers what paralysis can't do. It can't drain a gas tank. It can't leave two witnesses in the same front yard watching the same light. It can't put a car on the far side of an overpass with both occupants missing the same forty minutes. Sleep paralysis is real - REM atonia, chest pressure, the intruder hallucination, every century's wardrobe. I'll grant you every bedside case in my files. But the highway cases have physical anchors: fuel, mileage, a stopped watch, a second person. Paralysis is a solo act.",
   "tired": "... the literature covers it - and what paralysis can't do. it can't drain a gas tank. it can't leave two witnesses in the same yard watching the same light. it can't put a car on the far side of an overpass, both occupants missing the same forty minutes. paralysis is real - atonia, chest pressure, the intruder, every century's wardrobe. i'll grant every bedside case in my files. but the highway cases have physical anchors: fuel, mileage, a stopped watch, a second person... paralysis is a solo act.",
   "irritated": "The literature covers it - and what paralysis CAN'T do. It can't drain a gas tank. It can't leave two witnesses in the same front yard watching the same light. It can't put a car on the far side of an overpass with both occupants missing the same forty minutes. Sleep paralysis is real - REM atonia, chest pressure, the intruder hallucination. I'll grant you every bedside case in my files. But the highway cases have physical anchors: fuel, mileage, a stopped watch, a second person. Paralysis is a solo act.",
   "gruff": "Literature covers it - and what paralysis can't do. Can't drain a gas tank. Can't leave two witnesses in one yard watching one light. Can't put a car past an overpass, both occupants missing the same forty minutes. Paralysis is real - atonia, chest pressure, the intruder. Bedside cases - all yours. Highway cases have anchors: fuel, mileage, stopped watch, second person. Paralysis is a solo act.",
   "amused": "The literature covers it - and it covers what paralysis CAN'T do! It can't drain a gas tank! It can't leave two witnesses in the same front yard watching the same light! It can't put a car on the far side of an overpass with both occupants missing the same forty minutes! Sleep paralysis is real - REM atonia, chest pressure, the intruder hallucination, every century's wardrobe - and I'll grant you every bedside case in my files! But the highway cases have physical anchors: fuel, mileage, a stopped watch, a SECOND person! Paralysis is a solo act, doctor!",
   "focused": "The literature also documents paralysis's limits: it cannot drain fuel, cannot produce simultaneous independent witnesses, cannot relocate vehicles across an overpass with shared missing time in both occupants. The phenomenon is well characterized - REM atonia, chest pressure, intruder presence - and I concede every bedside case in the archive. Highway cases carry physical anchors: fuel consumption, odometer deltas, stopped timepieces, corroborating witnesses. Sleep paralysis is strictly individual.",
  }),
  ("c",
   "Physical anchors can be staged. Fuel can be mismeasured. Watches stop. And a second witness just means two people who fell asleep in the same room.",
   "Physical anchors can be staged, Vern. Fuel can be mismeasured. Watches stop. And a second witness just means two people who fell asleep in the same room, man."),
  ("v", {
   "neutral": "And a theory that can explain any evidence has stopped being a theory - it's a faith. So do me one favor, since you've clearly read the literature: pick a file. One file. The one with the strongest anchors - two cars, four witnesses, a fuel log - and paralyze that one. If you can, I'll read your breakdown on the air and half my file cabinet retires. That's not a brush-off. That's the only test any theory in this subject has ever passed.",
   "tired": "... a theory that can explain any evidence has stopped being a theory - it's a faith. so one favor, since you've read the literature: pick a file. one file. the one with the strongest anchors - two cars, four witnesses, a fuel log - and paralyze that one. if you can, i'll read your breakdown on the air and half my file cabinet retires. that's not a brush-off... that's the only test any theory here has ever passed.",
   "irritated": "A theory that can explain any evidence has stopped being a theory - it's a faith. One favor, since you've read the literature: pick a file. The one with the strongest anchors - two cars, four witnesses, a fuel log - and paralyze that one. If you can, I'll read your breakdown on the air and half my file cabinet retires. That's not a brush-off. That's the only test any theory in this subject has ever passed.",
   "gruff": "Theory that explains any evidence stopped being a theory - it's a faith. One favor, since you've read: pick a file. Strongest anchors - two cars, four witnesses, fuel log. Paralyze that one. If you can, I read your breakdown on air and half the cabinet retires. Not a brush-off. Only test any theory here ever passed.",
   "amused": "Ha - and a theory that can explain ANY evidence has stopped being a theory - it's a FAITH! So do me one favor, since you've clearly read the literature: pick a file! ONE file! The one with the strongest anchors - two cars, four witnesses, a fuel log - and paralyze THAT one! If you can, I'll read your breakdown on the air and half my file cabinet retires! That's not a brush-off, doctor - that's the only test any theory in this subject has ever passed!",
   "focused": "A hypothesis that absorbs all contrary evidence has exited science and entered doctrine. One request, given your command of the literature: select a single case file - maximal anchors: two vehicles, four witnesses, fuel documentation - and apply your model. Successful reduction will be broadcast, and half the archive reclassified. This is not deflection; it is the only validation standard this field has ever honored.",
  }),
  ("c",
   "Pick a file... alright. Send me the two-car one. If it survives paralysis, I'll call you back.",
   "Pick a file... alright. Send me the two-car one, Vern. If it survives paralysis, I'll, uh... I'll call you back."),
  ("v", {
   "neutral": "It goes out tonight - fuel log, witness statements, mileage, the works. Read it with the literature open on both sides. And if the file survives, call back - I'll hold the second hour for you. Thanks for calling, doctor.",
   "tired": "... goes out tonight - fuel log, witness statements, mileage. read it with the literature open on both sides. if the file survives, call back - i'll hold the second hour for you.",
   "irritated": "It goes out tonight - fuel log, witness statements, mileage. Read it with the literature open on both sides. If the file survives, call back - I'll hold the second hour for you. Thanks for calling.",
   "gruff": "Goes out tonight. Fuel log, statements, mileage. Read it with the literature open both sides. File survives - call back. Second hour's held for you.",
   "amused": "It goes out TONIGHT - fuel log, witness statements, mileage, the works! Read it with the literature open on both sides! And if the file survives, call back - I'll hold the second hour for you! Thanks for calling, doctor!",
   "focused": "Transmitted tonight: fuel documentation, witness affidavits, odometer records. Review with the sleep literature at hand. Should the case survive reduction, return to this line - the second-hour slot is reserved. Thank you for calling, doctor.",
  }),
 ],
},
{
 "arcId": "ufo_tin_hat_neighbor",
 "legitimacy": "Fake",
 "gender": "male",
 "personality": "gruff_experienced",
 "summary": "Man calls about his neighbor of fourteen years - since the ridge lights she has foil in three windows and won't come to barbecues",
 "notes": "Comedy opinion arc with a heart - no sighting, all neighbor worry (Fake: the subject is Dot, not the sky). Vern reframes: the lights didn't scare her, they gave her a language. His advice: two chairs, one evening, no foil jokes",
 "turns": [
  ("v", {
   "neutral": "You're on the air, and you're not calling about a light. You're calling about a neighbor.",
   "tired": "... you're on. not calling about a light. calling about a neighbor. go ahead.",
   "irritated": "You're on. Not calling about a light - calling about a neighbor. Go.",
   "gruff": "You're on. Not a light. A neighbor. Go.",
   "amused": "You're on the air and you're not calling about a light - you're calling about a NEIGHBOR! On this show! Go ahead, I'm listening.",
   "focused": "You're on the air. Your subject is a neighbor rather than an aerial phenomenon. Proceed.",
  }),
  ("c",
   "My neighbor of fourteen years. Since the ridge lights this spring, she's got foil in three of her windows and a notebook by the door. She stopped coming to barbecues. I'm not scared of the sky, Vern. I'm scared of what the sky did to Dot.",
   "My neighbor of fourteen years. Since the ridge lights this spring, she's got foil in three of her windows and a notebook by the door, man. She stopped coming to barbecues. I'm not scared of the sky, Vern. I'm scared of what the sky did to Dot, you know?"),
  ("v", {
   "neutral": "Foil in three windows and a notebook by the door. Has Dot told you what she actually saw?",
   "tired": "... foil in three windows, notebook by the door. has dot told you what she actually saw?",
   "irritated": "Foil in three windows, a notebook by the door. Has Dot told you what she actually saw?",
   "gruff": "Foil in three windows. Notebook by the door. Dot told you what she saw?",
   "amused": "Foil in three windows and a notebook by the door! Has Dot told you what she actually SAW?",
   "focused": "Foil in three windows; a notebook staged at the door. Has Dot disclosed her actual observations?",
  }),
  ("c",
   "That's just it - she won't say! Dot was a woman who watched ballgames and yelled at referees. Now she watches the sky every single night from that porch and won't tell a soul, and the foil went up the week after something did. Something happened to her out there. And nobody - not me, not her church, not you people - nobody asks her what.",
   "That's just it - she won't say! Dot was a woman who watched ballgames and yelled at referees, man. Now she watches the sky every single night from that porch and won't tell a soul, and the foil went up the week after something did. Something happened to her out there. And nobody - not me, not her church, not you people - nobody asks her what, you know?"),
  ("v", {
   "neutral": "Nobody asks her what - and you called the right line, just not for the reason you think. Twenty years of these calls taught me one thing: the lights didn't scare your neighbor. They gave her a language. People who watch the same ridge for forty years finally see something they can't explain, and some of them can't stop looking. The foil isn't fear of the sky - it's fear of being interrupted. You want Dot back? Don't ask about the foil. Take two chairs to that porch, sit down one evening, and ask her to show you what she looks at. Witnesses are lonelier than anyone knows, and Dot's had fourteen years of you not asking without laughing.",
   "tired": "... nobody asks her what - and you called the right line, just not for the reason you think. twenty years of these calls taught me one thing: the lights didn't scare your neighbor. they gave her a language. people who watch the same ridge for forty years finally see something they can't explain, and some of them can't stop looking. the foil isn't fear of the sky - it's fear of being interrupted. you want dot back? don't ask about the foil. take two chairs to that porch, sit down one evening, ask her to show you what she looks at. witnesses are lonelier than anyone knows... and dot's had fourteen years of you not asking without laughing.",
   "irritated": "Nobody asks her what - and you called the right line, just not for the reason you think. Twenty years of these calls taught me one thing: the lights didn't scare your neighbor, they gave her a language. People who watch the same ridge for forty years finally see something they can't explain, and some can't stop looking. The foil isn't fear of the sky - it's fear of being interrupted. You want Dot back? Don't ask about the foil. Two chairs, that porch, one evening - ask her to show you what she looks at. Witnesses are lonelier than anyone knows, and Dot's had fourteen years of you not asking without laughing.",
   "gruff": "Nobody asks her what. Right line, wrong reason. Twenty years of these calls: the lights didn't scare your neighbor. Gave her a language. Folks watch the same ridge forty years, finally see something they can't explain, some can't stop looking. Foil isn't fear of the sky - fear of being interrupted. Want Dot back? Don't ask about the foil. Two chairs, that porch, one evening - ask her to show you what she looks at. Witnesses are lonelier than anyone knows. Dot's had fourteen years of you not asking without laughing.",
   "amused": "Ha - nobody asks her what! You called the right line, just not for the reason you think! Twenty years of these calls taught me one thing: the lights didn't SCARE your neighbor - they gave her a language! People who watch the same ridge for forty years finally see something they can't explain, and some of them can't stop looking! The foil isn't fear of the sky - it's fear of being INTERRUPTED! You want Dot back? Don't ask about the foil! Take two chairs to that porch, sit down one evening, and ask her to show you what she looks at! Witnesses are lonelier than anyone knows, my friend - and Dot's had fourteen years of you not asking without laughing!",
   "focused": "'Nobody asks her what' - you reached the correct program for the wrong reason. Two decades of case calls yield one pattern: the phenomenon did not frighten your neighbor; it gave her a framework. Long-term observers of a fixed vista who encounter the inexplicable often fixate. The foil addresses interruption risk, not aerial threat. Recommended intervention: two chairs, her porch, one evening - request she demonstrate her observation routine. Witnesses experience profound isolation; Dot has had fourteen years of unasked, unlaughed-for company.",
  }),
  ("c",
   "Without laughing... she used to laugh at your show, you know. Every night, ballgame on mute, she'd laugh at you people. Now she IS you people. And I miss her.",
   "Without laughing... she used to laugh at your show, you know. Every night, ballgame on mute, she'd laugh at you people, man. Now she IS you people. And I, uh... I miss her."),
  ("v", {
   "neutral": "You miss her - so go get her. And I'll tell you something that doesn't make the ballgames easier: nobody sits down at this table on purpose. Dot didn't choose the ridge; the ridge chose Dot. The ones who laugh hardest at this show are the ones who haven't looked up on the right night yet. Two chairs, one evening, no jokes about the foil. Ask her what she sees. And if she shows you - and some nights, she might show you something - you call me. Both of you.",
   "tired": "... you miss her - so go get her. and something that doesn't make the ballgames easier: nobody sits down at this table on purpose. dot didn't choose the ridge. the ridge chose dot. the ones who laugh hardest at this show are the ones who haven't looked up on the right night yet. two chairs, one evening, no jokes about the foil. ask her what she sees. and if she shows you something... call me. both of you.",
   "irritated": "You miss her - so go get her. And something that doesn't make the ballgames easier: nobody sits down at this table on purpose. Dot didn't choose the ridge; the ridge chose Dot. The ones who laugh hardest at this show are the ones who haven't looked up on the right night yet. Two chairs, one evening, no jokes about the foil. Ask her what she sees. And if she shows you something - call me. Both of you.",
   "gruff": "You miss her - go get her. And this doesn't make the ballgames easier: nobody sits at this table on purpose. Dot didn't choose the ridge. The ridge chose Dot. Loudest laughers at this show haven't looked up on the right night yet. Two chairs, one evening, no foil jokes. Ask her what she sees. She shows you something - call me. Both of you.",
   "amused": "You miss her - so GO GET HER! And I'll tell you something that doesn't make the ballgames easier: nobody sits down at this table on purpose! Dot didn't choose the ridge - the ridge chose DOT! The ones who laugh hardest at this show are the ones who haven't looked up on the right night yet! Two chairs, one evening, no jokes about the foil! Ask her what she sees - and if she shows you something, and some nights she might - you call me! Both of you!",
   "focused": "You miss her - retrieve her. One observation that will not ease the ballgames: participation in this subject is never elective. Dot did not select the ridge; the ridge selected Dot. The loudest critics of this program are those who have not observed on the correct night. Protocol: two chairs, one evening, zero foil commentary. Request her observations. Should she demonstrate something substantive, contact this line - jointly.",
  }),
  ("c",
   "Both of us... alright. Two chairs. No foil jokes. And Vern - if she shows me something... I don't know what I'll do.",
   "Both of us... alright. Two chairs. No foil jokes. And Vern - if she shows me something... I, uh... I don't know what I'll do, man."),
  ("v", {
   "neutral": "If she shows you something, you'll do what everybody does who's ever been shown: you'll sit with it a while, and then you'll have to tell somebody. That's what this line is for. Go sit on your neighbor's porch - the sky can wait. Thanks for calling.",
   "tired": "... if she shows you something, you'll do what everybody does who's ever been shown: sit with it a while, then have to tell somebody. that's what this line's for. go sit on your neighbor's porch... the sky can wait.",
   "irritated": "If she shows you something, you'll do what everybody does who's ever been shown: you'll sit with it a while, and then you'll have to tell somebody. That's what this line is for. Go sit on your neighbor's porch - the sky can wait. Thanks for calling.",
   "gruff": "She shows you something, you'll do what everybody does who's been shown: sit with it, then have to tell somebody. That's what this line's for. Go sit on your neighbor's porch. Sky can wait.",
   "amused": "If she shows you something, you'll do what everybody does who's ever been shown: you'll sit with it a while - and then you'll HAVE to tell somebody! That's what this line is for! Go sit on your neighbor's porch, my friend - the sky can wait! Thanks for calling!",
   "focused": "Should she demonstrate something, you will follow the universal pattern: extended processing, then compelled disclosure. This line exists for that disclosure. Proceed to your neighbor's porch - the sky will keep. Thank you for calling.",
  }),
 ],
},
]
