# -*- coding: utf-8 -*-
# Batch 2 content (part 1): opinion wave 2.
ARCS = [
{
 "arcId": "ufo_math_doesnt_add_up",
 "legitimacy": "Questionable",
 "gender": "male",
 "personality": "cold_factual",
 "summary": "Accountant argues interstellar distances make alien visitors mathematically absurd",
 "notes": "Opinion caller with a real argument. Vern concedes the arithmetic, then shows it only kills ONE hypothesis - the 2004 object was already here. Ends with an invitation to bring numbers",
 "turns": [
  ("v", {
   "neutral": "You're on the air. You said you've done the math on all of this.",
   "tired": "... you're on. you've done the math. alright, let's hear it.",
   "irritated": "You're on. You've done the math - go on then.",
   "gruff": "You're on. The math. Go.",
   "amused": "You're on the air with MATH! Finally, somebody brought homework. Go on.",
   "focused": "You're on the air. Present your calculations.",
  }),
  ("c",
   "I'm a certified accountant, thirty-one years. I ran the numbers on the distances. The nearest star is four-point-two light years out. At anything humanity has ever built, that trip is thousands of years, each way, for a crew that dies en route. Nobody crosses that for a cornfield in Nebraska. Your space aliens are a math problem that doesn't solve. End of story.",
   "I'm a certified accountant, thirty-one years. I ran the numbers on the distances. The nearest star is four-point-two light years out. At anything humanity has ever built, that trip is, uh... thousands of years, each way, for a crew that dies en route. Nobody crosses that for a cornfield in Nebraska. Your space aliens are a math problem that doesn't solve. End of story, I mean."),
  ("v", {
   "neutral": "Good arithmetic. Now tell me - where in any of my files does it say they came FROM another star?",
   "tired": "... good arithmetic. now tell me - where in my files does it say they came from another star?",
   "irritated": "Good arithmetic. Now answer one thing - where in any of my files does it say they came from another star?",
   "gruff": "Good arithmetic. Where in my files does it say they came from another star?",
   "amused": "Ha! Good arithmetic - genuinely. Now tell me: where in any of my files does it say they came FROM another star?",
   "focused": "The arithmetic is sound. Now identify the premise: which file claims interstellar origin?",
  }),
  ("c",
   "They're flying saucers! That's the whole premise of the subject! If they're not from another star, then they're from here - and if they're from here, then it's us, and that's some other caller's theory, not mine.",
   "They're flying saucers! That's the whole premise of the subject! If they're not from another star, then they're from here - and if they're from here, then it's us, and that's, uh... that's some other caller's theory, not mine."),
  ("v", {
   "neutral": "Here's the part your math didn't touch. The object off San Diego in 2004 didn't fly in from another star that afternoon - it was already here. In our airspace, on a warship's radar, then gone. Distances argue against interstellar tourism. They say nothing about something already parked in this system - an ocean, an orbit nobody watches. Serious people disagree about where. They don't disagree about whether. Your arithmetic killed one hypothesis. There are more shelves in this store.",
   "tired": "... here's what your math didn't touch. the object off san diego in 2004 didn't fly in from another star that afternoon - it was already here. in our airspace, on a warship's radar, then gone. distances argue against interstellar tourism. they say nothing about something already parked here. your arithmetic killed one hypothesis... there are more shelves in this store.",
   "irritated": "Here's what your math didn't touch. The 2004 object off San Diego didn't fly in from another star that afternoon - it was already here, on a warship's radar. Distances argue against interstellar tourism, not against something already parked in this system. Your arithmetic killed one hypothesis. There are more shelves in the store.",
   "gruff": "Your math didn't touch the part that matters. 2004, San Diego - already here. Our airspace, warship radar. Distances kill interstellar tourism. They don't kill something parked in this system. One hypothesis down. More shelves in the store.",
   "amused": "Ah, here's the part your math never touched! The object off San Diego in 2004 didn't fly in from another star that afternoon - it was ALREADY HERE. In our airspace, on a warship's radar, and then gone! Distances argue against interstellar tourism - they say nothing about something already parked in this system, in an ocean, in an orbit nobody watches! Your arithmetic killed one hypothesis, my friend. There are more shelves in this store!",
   "focused": "Your model addresses interstellar transit only. The 2004 San Diego encounter involves an object already present in terrestrial airspace, tracked by naval radar - no transit component required. Distance arguments constrain origin hypotheses, not presence. Candidates include oceanic staging and unmonitored orbits. Your arithmetic falsifies one hypothesis class; the case file spans several.",
  }),
  ("c",
   "More shelves in the store... alright. But you're still left with 'trust me' - no propulsion, no fuel, no mechanism. My side has arithmetic. What does yours have?",
   "More shelves in the store... alright, fine. But you're still left with, uh... 'trust me' - no propulsion, no fuel, no mechanism. My side has arithmetic. What does yours have?"),
  ("v", {
   "neutral": "The opposite of trust me. Mine has sensor data - radar tracks, gun camera video, sworn aviators testifying to Congress. That's more than the arithmetic side has, which is calculations plus an assumption about where they started. When your side brings me a track, we'll compare them. Until then, the math stays in its lane.",
   "tired": "... the opposite of trust me. mine has sensor data - radar tracks, gun camera video, pilots under oath to congress. that's more than the arithmetic side has - calculations plus an assumption about where they started. when your side brings a track, we'll compare...",
   "irritated": "The opposite of trust me. Mine has sensor data - radar tracks, gun camera video, sworn aviators before Congress. Yours has calculations plus an assumption about where they started. Bring me a track and we'll compare. Until then, the math stays in its lane.",
   "gruff": "Opposite of trust me. Sensor data. Radar tracks, gun camera, pilots under oath. Your side's got calculations plus an assumption. Bring a track, we'll compare. Math stays in its lane till then.",
   "amused": "Ha - the OPPOSITE of trust me! Mine has sensor data: radar tracks, gun camera video, sworn aviators testifying to Congress! That's more than the arithmetic side has, which is calculations plus one big assumption about where they started! When your side brings me a track, we'll compare them - until then, the math stays in its lane!",
   "focused": "Evidentiary basis: multi-sensor radar tracks, gun camera footage, and sworn congressional testimony from naval aviators. Your model rests on arithmetic plus an unexamined origin assumption. When your side produces a comparable track, the datasets can be reconciled. Until then, the distance argument is out of scope.",
  }),
  ("c",
   "A track... look, I'll give you this: you're the first host who didn't shout God at me. I'll think about the shelves. I'm not promising anything.",
   "A track... look, I'll give you this much - you're the first host who didn't, uh... shout God at me. I'll think about the shelves. I'm not promising anything, though."),
  ("v", {
   "neutral": "Think about them - and when you do, bring me the accountant's version: costs, distances, what it would take to park something in this system and keep it quiet. The line's open for that. Numbers are welcome here. It's the certainty I check at the door. Thanks for calling.",
   "tired": "... think about them. and when you do, bring me the accountant's version - costs, distances, what it'd take to park something here and keep it quiet. numbers are welcome. it's the certainty i check at the door.",
   "irritated": "Think about them. And when you do, bring the accountant's version - costs, distances, what it takes to park something here quietly. Numbers are welcome. Certainty gets checked at the door. Thanks for calling.",
   "gruff": "Think. Then bring me the accountant's version - costs, distances, logistics. Numbers welcome. Certainty checked at the door. Thanks for calling.",
   "amused": "Think about them! And when you do, bring me the accountant's version - costs, distances, what it would take to park something in this system and keep it quiet! The line's open for that. Numbers are always welcome here - it's the certainty I check at the door! Thanks for calling!",
   "focused": "Proceed with the analysis. The next step is a logistics model: staging costs, detection avoidance, sustainment in-system. This line accepts quantitative submissions. Numbers are welcome; certainty is screened at intake. Thank you for calling.",
  }),
 ],
},
{
 "arcId": "ufo_demons_not_aliens",
 "legitimacy": "Fake",
 "gender": "female",
 "personality": "official",
 "summary": "Church elder declares the lights are demons and the broadcast is an invitation into every kitchen",
 "notes": "Opinion caller - sincere but unfalsifiable (Fake: asserts spiritual causation as fact, no evidence offered). Vern is respectful, shares the Vatican observatory + pastors-on-the-line history, reframes the show as a phone line not a door. She softens slightly",
 "turns": [
  ("v", {
   "neutral": "You're on the air. You called about what this show is inviting into people's homes.",
   "tired": "... you're on. what the show's inviting into homes. go ahead.",
   "irritated": "You're on. Something about what we're inviting into homes. Go.",
   "gruff": "You're on. The inviting thing. Go.",
   "amused": "You're on the air, and you've come to tell me what I'm inviting into people's homes! Alright - I'm listening.",
   "focused": "You're on the air. State your concern about the program's influence.",
  }),
  ("c",
   "I'm a church woman, and I'll give you the plain truth: they are demons. Fallen ones. The lights, the voices in the night, the missing hours - it is the old enemy in a new costume, and your program broadcasts an invitation into every kitchen in this county.",
   "I'm a church woman, and I'll give you the plain truth: they are demons. Fallen ones. The lights, the voices in the night, the missing hours - it is all the old enemy in a new costume. And your program, um... your program broadcasts an invitation into every kitchen in this county."),
  ("v", {
   "neutral": "Then tell me this, ma'am - why would the old enemy need a radio station in a town with one traffic light?",
   "tired": "... then tell me this, ma'am - why would the old enemy need a radio station in a town with one traffic light?",
   "irritated": "Then explain this - why would the old enemy need a radio station in a town with one traffic light?",
   "gruff": "Why would the old enemy need a radio station in a town with one traffic light?",
   "amused": "Then answer me this, ma'am - why would the old enemy need a radio station in a town with ONE traffic light?",
   "focused": "Then address the logistics: why would an ancient adversary require a small-market broadcast to operate?",
  }),
  ("c",
   "Mockery suits you about as well as it suits him. The enemy has always used the fashionable vessel - the serpent, the stage, the moving pictures. Now it's the airwaves. My pastor says every generation gets a new door, and this generation's door has your call letters on it.",
   "Mockery suits you about as well as it suits him. The enemy has always used the fashionable vessel - the serpent, the stage, the moving pictures. And now it's the airwaves. My pastor says, um... every generation gets a new door, and this generation's door has your call letters on it."),
  ("v", {
   "neutral": "Your pastor and I would agree more than you think - I've had pastors on this very line, and a few of them called about what they saw themselves. The churches have investigated too: the Vatican has kept an observatory for centuries - men of God at the eyepiece. And here's what this line actually is: it doesn't ask belief, it asks honesty. Half my callers think it's drones. A quarter think it's the end times. They all get the same thing - an open phone and a straight question. That's not an invitation to anything. It's the opposite of one.",
   "tired": "... your pastor and i would agree more than you think. i've had pastors on this line - a couple called about what they saw themselves. the churches have investigated: the vatican's kept an observatory for centuries. men of god at the eyepiece. and this line doesn't ask belief. it asks honesty. half my callers think drones. a quarter think end times. they all get an open phone and a straight question. that's not an invitation... it's the opposite.",
   "irritated": "Your pastor and I would agree more than you think. I've had pastors on this line - some called about what they saw themselves. The churches investigate: the Vatican has kept an observatory for centuries. And this line doesn't ask belief, it asks honesty. Half my callers think drones, a quarter think end times - they all get an open phone and a straight question. That's not an invitation. It's the opposite.",
   "gruff": "Your pastor and I agree more than you think. Had pastors on this line - two called about their own sightings. Vatican's kept an observatory for centuries. Men of God at the eyepiece. This line doesn't ask belief. Asks honesty. Drones, end times - everybody gets an open phone and a straight question. Not an invitation. Opposite.",
   "amused": "Ha - your pastor and I would agree more than you think! I've had pastors on this very line, and a couple called about what they saw themselves! And the churches investigate, ma'am - the Vatican has kept an observatory for CENTURIES. Men of God at the eyepiece! Here's what this line is: it doesn't ask belief, it asks honesty. Half my callers think it's drones, a quarter think it's the end times, and they all get the same open phone and straight question. That's not an invitation - it's the opposite of one!",
   "focused": "Your pastor and I share more common ground than assumed: clergy have appeared on this line, including witnesses reporting their own observations. Institutional religion investigates as well - the Vatican Observatory has operated for centuries. This program requests honesty, not belief. Reporters span the spectrum from drone attribution to eschatology, and all receive identical treatment: an open line and neutral questioning. That is the antithesis of an invitation.",
  }),
  ("c",
   "A straight question... you honestly believe that? That you're not feeding something, just by asking?",
   "A straight question... you honestly believe that? That you're not, um... feeding something, just by asking?"),
  ("v", {
   "neutral": "I believe the lights were there before this line and they'll be there after I'm gone. The question is whether people face them alone in a kitchen at 2 AM - or with a hundred thousand neighbors on the phone. I know which one I'd want for my mother. Keep your faith, ma'am; it's carried more people through the dark than my transmitter ever will. Just don't mistake a phone line for a door.",
   "tired": "... i believe the lights were there before this line, and they'll be there after i'm gone. the question is whether people face them alone in a kitchen at 2 AM, or with a hundred thousand neighbors on the phone. i know which i'd want for my mother. keep your faith, ma'am... it's carried more people through the dark than my transmitter ever will. don't mistake a phone line for a door.",
   "irritated": "I believe the lights were here before this line and they'll be here after I'm gone. The question is whether people face them alone in a kitchen at 2 AM or with a hundred thousand neighbors on the phone. I know which I'd want for my mother. Keep your faith - it's carried more people through the dark than my transmitter ever will. Don't mistake a phone line for a door.",
   "gruff": "Lights were here before this line. They'll be here after me. Question's whether folks face them alone at 2 AM, or with a hundred thousand neighbors on the phone. I know which I'd want for my mother. Keep your faith, ma'am - it's carried more people than my transmitter. Don't mistake a phone line for a door.",
   "amused": "I believe the lights were there before this line and they'll be there after I'm gone! The only question is whether folks face them ALONE in a kitchen at 2 AM - or with a hundred thousand neighbors on the phone! I know which one I'd want for my mother! Keep your faith, ma'am - it's carried more people through the dark than my transmitter ever will. Just don't mistake a phone line for a door!",
   "focused": "The phenomenon predates this broadcast and will outlast it. The operative variable is isolation: witnesses facing it alone at 2 AM versus witnesses connected to a hundred thousand simultaneous listeners. For my own mother, the choice is obvious. Your faith has sustained more people through darkness than this transmitter ever will - simply do not conflate a phone line with a door.",
  }),
  ("c",
   "A phone line, not a door... I don't know that you're wrong. But I'll still be praying for this station.",
   "A phone line, not a door... I don't know that you're wrong. But I'll still be praying for this station, you know that."),
  ("v", {
   "neutral": "I'll take the prayers - heaven knows the transmitter needs them. And ma'am? If you ever see something yourself, this line is here for you too. No sermon required. Thanks for calling.",
   "tired": "... i'll take the prayers - heaven knows the transmitter needs them. and ma'am... if you ever see something yourself, this line's here too. no sermon required.",
   "irritated": "I'll take the prayers - the transmitter needs them. And ma'am, if you ever see something yourself, this line's here. No sermon required. Thanks for calling.",
   "gruff": "I'll take the prayers - transmitter needs them. And if you ever see something yourself, the line's here. No sermon required.",
   "amused": "I'll take the prayers - heaven knows this transmitter needs them! And ma'am? If you ever see something yourself, this line is here for you too. No sermon required! Thanks for calling.",
   "focused": "The prayers are accepted - the transmitter has earned them. Should you ever observe something yourself, this line remains available. No sermon required. Thank you for calling.",
  }),
 ],
},
{
 "arcId": "ufo_time_travelers",
 "legitimacy": "Questionable",
 "gender": "male",
 "personality": "enthusiastic_convert",
 "summary": "Convert to the future-humans theory - the visitors are time tourists from our own descendants",
 "notes": "Opinion caller, excited, well-read but uncritical. Vern shares Vallée's control-system idea and the theory's real history, concedes its strengths, then names the honest cost (unfalsifiable) and rewards the hopeful reading",
 "turns": [
  ("v", {
   "neutral": "You're on the air. You told the screener you've solved where they come from - and it isn't a where.",
   "tired": "... you're on. you've solved where they come from. and it isn't a where. alright.",
   "irritated": "You're on. You've solved where they come from - and it's not a where. Explain.",
   "gruff": "You're on. Not a where. Go.",
   "amused": "You're on the air with a solved mystery - and it's not a WHERE! Alright, now I'm invested. Go on.",
   "focused": "You're on the air. You claim to have resolved the origin question. State your thesis.",
  }),
  ("c",
   "It's a when. Vern - they're not visitors, they're us. From later. Time tourists coming back to watch their own history the way we visit battlefields. It explains everything: they look like people, they speak, they take folks and bring them back, they show up at the important moments. Nobody crosses four light years for a cornfield - they cross forty years!",
   "It's a when, man. Vern - they're not visitors, they're us. From later. Like, time tourists coming back to watch their own history the way we visit battlefields, you know? It explains everything: they look like people, they speak, they take folks and bring them back, they show up at the important moments. Nobody crosses four light years for a cornfield - they cross forty years!"),
  ("v", {
   "neutral": "You've been reading. That theory is older than this show - who put you onto it?",
   "tired": "... you've been reading. that theory's older than this show. who put you onto it?",
   "irritated": "You've been reading. That theory predates this show - who gave it to you?",
   "gruff": "You've been reading. Who put you onto it?",
   "amused": "Ha - you've been READING! That theory's older than this show. Who put you onto it?",
   "focused": "That hypothesis predates this program. Identify your source.",
  }),
  ("c",
   "I found it myself! I mean - okay, I found a paperback at a library sale, from the seventies, and then I couldn't stop. There's a whole shelf of it. Vallée - he called it a control system, said the phenomenon manages what people believe. And the future-humans people. Vern, the shelf was huge and nobody told me about any of it. I found it.",
   "I found it myself! I mean - okay, I found a paperback at a library sale, from the seventies, and then I couldn't stop. There's a whole shelf of it. Vallée - he called it a control system, said the phenomenon, like, manages what people believe. And the future-humans people. Vern, the shelf was huge and nobody told me about any of it. I found it."),
  ("v", {
   "neutral": "Here's my take, and I've given it to every time-traveler who ever called: the theory earns its keep. It explains the human resemblance, the languages they seem to know, why people get taken and put back. Vallée spent fifty years arguing the phenomenon behaves like a thermostat for belief - keeping it at a set temperature. But here's the honest cost: it trades one impossible engine for another. Interstellar travel is hard physics. Time travel is harder physics. And neither one explains the radar tracks - a thing that fools two radars isn't running on belief alone.",
   "tired": "... my take, and i've given it to every time-traveler who called: the theory earns its keep. explains the human resemblance, the languages, why folks get taken and put back. vallée spent fifty years saying the phenomenon's like a thermostat for belief. but the honest cost: it trades one impossible engine for another. interstellar is hard physics. time travel is harder. and neither explains radar tracks... a thing that fools two radars isn't running on belief alone.",
   "irritated": "My take, and I've given it to every time-traveler who called: the theory earns its keep. It explains the human resemblance, the languages, why people get taken and put back. Vallée spent fifty years arguing it behaves like a thermostat for belief. But the honest cost: it trades one impossible engine for another. Interstellar travel is hard physics; time travel is harder. And neither explains the radar tracks.",
   "gruff": "My take: theory earns its keep. Explains the human resemblance, the languages, take-and-return. Vallée - fifty years - called it a thermostat for belief. Honest cost: trades one impossible engine for another. Interstellar's hard physics. Time travel's harder. Neither explains radar tracks.",
   "amused": "Here's my take, and I've given it to every time-traveler who ever called: the theory EARNS its keep! It explains the human resemblance, the languages they seem to know, why folks get taken and put right back! Vallée spent fifty years arguing the phenomenon works like a thermostat for belief! But here's the honest cost, and I mean it: it trades one impossible engine for another. Interstellar travel is hard physics - time travel is HARDER physics! And neither one explains the radar tracks. A thing that fools two radars isn't running on belief alone!",
   "focused": "Assessment: the hypothesis has explanatory power - human resemblance, apparent language comprehension, and the take-and-return pattern all fit. Vallée's fifty-year control-system model frames the phenomenon as belief regulation. The honest cost: it substitutes one infeasible propulsion for a less feasible one. Interstellar transit is hard physics; closed timelike curves are harder. Neither accounts for dual-radar returns.",
  }),
  ("c",
   "But that's just it - if they're us, then they're already as good as we are, and we get better! Give humanity forty years! The radar thing isn't a hole in my theory - it's proof they solved it!",
   "But that's just it - if they're us, then they're already as good as we are, and we get better! Give humanity forty years! The radar thing isn't a hole in my theory - it's, like... it's proof they solved it!"),
  ("v", {
   "neutral": "Proof they solved it - I'm going to write that down, because that is the most hopeful thing a caller has ever said on this program, and it is also unfalsifiable, which is where I have to draw my line. A theory that explains everything has paid for nothing. But I'll tell you what your shelf changed for me: how I read a witness. If the future is visiting, then nobody who saw something is a crackpot - they're early. And that is worth every library sale in the state.",
   "tired": "... proof they solved it. i'm writing that down - most hopeful thing a caller's ever said here. and unfalsifiable, which is where i draw my line. a theory that explains everything has paid for nothing. but i'll tell you what your shelf changed: how i read a witness. if the future is visiting, nobody who saw something's a crackpot... they're early. worth every library sale in the state.",
   "irritated": "Proof they solved it - I'm writing that down, because it's the most hopeful thing a caller ever said here, and it's unfalsifiable, which is where I draw the line. A theory that explains everything has paid for nothing. But your shelf changed how I read a witness: if the future is visiting, nobody who saw something is a crackpot. They're early.",
   "gruff": "Proof they solved it. Most hopeful thing a caller ever said here. Also unfalsifiable - that's my line. A theory that explains everything paid for nothing. But your shelf changed how I read witnesses. If the future's visiting, nobody who saw something's a crackpot. They're early.",
   "amused": "Ha - PROOF they solved it! I'm writing that down, because that is the most hopeful thing a caller has ever said on this program! And it is also unfalsifiable, which is where I have to draw my line - a theory that explains everything has paid for nothing! But I'll tell you what your shelf changed for me: how I read a witness. If the future is visiting, then nobody who saw something is a crackpot - they're EARLY. And that is worth every library sale in the state!",
   "focused": "Note: that claim is the most optimistic this program has received - and unfalsifiable, which sets my boundary. A theory explaining everything costs nothing. However, your reading list changed my witness assessment: under the future-visitor model, observers are not unreliable - they are premature. That reframing has genuine analytical value.",
  }),
  ("c",
   "They're early... Vern, that's - nobody has ever put it like that. I'm telling my whole reading group.",
   "They're early... Vern, that's - uh, nobody has ever put it like that. I'm telling my whole reading group, man."),
  ("v", {
   "neutral": "Tell them, and bring me the book list - this show could use a reading group. Keep the shelf growing, son. And when you find the one book that explains the radar, you call this line before anybody else. Thanks for calling.",
   "tired": "... tell them. bring me the book list - this show could use a reading group. keep the shelf growing. and when you find the one book that explains the radar... call this line first.",
   "irritated": "Tell them - and bring me the book list, this show could use a reading group. Keep the shelf growing. And when you find the one book that explains the radar, call this line first. Thanks for calling.",
   "gruff": "Tell them. Bring me the book list. Keep the shelf growing. Find the book that explains radar - call me first.",
   "amused": "Tell them - and bring me the book list, because this show could use a reading group! Keep that shelf growing, son! And when you find the one book that explains the radar? You call this line before anybody else! Thanks for calling!",
   "focused": "Share it with them, and submit the bibliography - this program would benefit from a reading group. Continue expanding the shelf. When you locate a source that accounts for the radar returns, contact this line first. Thank you for calling.",
  }),
 ],
},
]
