# -*- coding: utf-8 -*-
# Batch 1 content (part 2): opinion wave 1.
ARCS = [
{
 "arcId": "ufo_hollywood_poisoned",
 "legitimacy": "Fake",
 "gender": "male",
 "personality": "charismatic_storyteller",
 "summary": "Screenwriter insists every caller is regurgitating Close Encounters - saucers are a studio product",
 "notes": "Opinion caller, confidently wrong (Fake: zero data, pure assertion). Vern counters with the shape-wave history: foo fighters, discs predate film, triangles predate film, orbs track cameras. Concedes contagion is real, demands a patient zero",
 "turns": [
  ("v", {
   "neutral": "You're on the air. You told the screener you know exactly where saucers come from, and it isn't the sky.",
   "tired": "... you're on. you know where saucers come from. not the sky. where?",
   "irritated": "You're on. You claim to know where saucers come from. Enlighten us.",
   "gruff": "You're on. Where do saucers come from?",
   "amused": "You're on the air and you've solved the whole mystery - saucers aren't from the sky! Do tell.",
   "focused": "You're on the air. State your thesis on the origin of the saucer shape.",
  }),
  ("c",
   "Hollywood. That's it, that's the answer. I write for a living, Vern - I've sat in the rooms. The saucer is a studio product, and every caller you've ever had is describing a movie they saw when they were eight. The lights, the hum, the little gray men - that's a shot list, not a memory.",
   "Hollywood. That's it, that's the answer. I write for a living, Vern - I've, uh... I've sat in the rooms. The saucer is a studio product, and every caller you've ever had is describing a movie they saw when they were eight. The lights, the hum, the little gray men - that's, like... that's a shot list, not a memory."),
  ("v", {
   "neutral": "You write for a living, so answer me one thing - when did Hollywood make the saucer?",
   "tired": "... a writer, huh. then answer this - when did hollywood make the saucer?",
   "irritated": "You're a writer? Good. Answer one thing - when did Hollywood make the saucer?",
   "gruff": "Writer, huh. When did Hollywood make the saucer?",
   "amused": "A man of the industry on my line! Then humor me - when exactly did Hollywood make the saucer?",
   "focused": "You work in film. Then date the invention. When did Hollywood make the saucer?",
  }),
  ("c",
   "Well - the flying discs, '47, the pictures followed inside a year, everybody knows that. But that's not the point. The point is what people remember. Nobody remembers a light in the sky. People remember Close Encounters, they remember the abduction scene from Fire in the Sky, and then they dress up Aunt Ruth's light story in Spielberg's wardrobe.",
   "Well - the flying discs, '47, the pictures followed inside a year, everybody knows that. But that's not the point. The point is what people remember. Nobody remembers a light in the sky, man. People remember Close Encounters, they remember the, uh... the abduction scene from Fire in the Sky, and then they dress up Aunt Ruth's light story in Spielberg's wardrobe."),
  ("v", {
   "neutral": "Here's what my file cabinets say, and I've got forty years of them: the shapes come in waves. Foo fighters in the war - glowing balls, before any movie. Discs from '47 - the pictures came after, not before. Big silent triangles through the eighties and nineties - decades before Hollywood made a triangle anybody remembers. And now? Orbs and tic-tacs. The shapes changed when the cameras changed, not when the movies changed. Your Aunt Ruth theory explains why the stories rhyme. It doesn't explain why the shapes keep moving first.",
   "tired": "... forty years of files. shapes come in waves. foo fighters in the war, before any movie. discs from '47 - pictures came after. big triangles in the eighties, decades before hollywood caught up. now orbs. shapes move when cameras move. your theory explains why the stories rhyme... it doesn't explain why the shapes move first.",
   "irritated": "Forty years of files say the shapes come in waves. Foo fighters over the war - before any movie. Discs from '47 - the movies followed. Big silent triangles in the eighties, decades before Hollywood had one worth remembering. Orbs now. Shapes move when cameras move, not when studios do. Your theory explains rhyming stories, not moving shapes.",
   "gruff": "Forty years of files. Shapes come in waves. Foo fighters in the war, before movies. Discs from '47 - movies followed. Triangles in the eighties, decades before Hollywood caught up. Orbs now. Shapes move when cameras move. Your theory explains rhyming stories. Not moving shapes.",
   "amused": "Oh, let me read you the file cabinets - forty years of them! Foo fighters over the war, glowing balls, before a single movie! Discs from '47 - the pictures came after, not before! Big silent triangles all through the eighties, decades before Hollywood made one worth remembering! And now? Orbs and tic-tacs! The shapes change when the cameras change, my friend - your theory explains why the stories rhyme, but not why the shapes keep moving first!",
   "focused": "The archival record shows shape succession: foo fighters 1944-45, predating film depiction. Discs from 1947, with cinema following within a year - effect after cause. Large silent triangles through the 1980s-90s, preceding any culturally dominant triangle depiction by decades. Current reports favor orbs. Shape transitions correlate with sensor technology, not release schedules. Your hypothesis accounts for narrative convergence but not morphological succession.",
  }),
  ("c",
   "Okay, okay - the triangles are a wrinkle, I'll give you the triangles. But you're still running a show where every caller sounds like they read the same book, because they did - they read each other. Contagion. That's all a sighting wave ever is: one story infecting a county.",
   "Okay, okay - the triangles are a wrinkle, I'll give you the triangles. But you're still running a show where every caller sounds like they read the same book, because they did - they read each other, man. Contagion. That's all a sighting wave ever is: one story, uh... infecting a county."),
  ("v", {
   "neutral": "Contagion is real - it's in every serious book on this, including the ones I like. Waves follow the news: the '73 flap started with two kids in Mississippi and the phones rang for months. But contagion needs a patient zero who saw something first. Your job, since you're a writer - ask why patient zero keeps being somebody who gains nothing. Farmers. Deputies. Night nurses. Liars cast so much better. Witnesses just... are.",
   "tired": "... contagion's real, it's in every good book on this. waves follow the news - the '73 flap started with two kids and the phones rang for months. but contagion needs a patient zero who saw something first. ask why zero keeps being somebody who gains nothing. farmers. deputies. nurses. liars cast better. witnesses just... are.",
   "irritated": "Contagion's real - it's in every serious book on this. Waves follow news; the '73 flap started with two kids and ran for months. But contagion needs a patient zero who saw something first. And ask yourself why patient zero keeps being somebody who gains nothing - farmers, deputies, nurses. Liars cast better.",
   "gruff": "Contagion's real. Every good book says so. '73 flap - two kids, months of calls. But it needs a patient zero who saw something first. Ask why zero keeps being people who gain nothing. Farmers. Deputies. Nurses. Liars cast better.",
   "amused": "Now you're in my file cabinet! Contagion IS real - the '73 flap started with two boys in Mississippi and the lines rang for months! But here's the rub, writer: every contagion needs a patient zero who saw something first. And ask yourself why patient zero keeps being a farmer, a deputy, a night nurse - people who get nothing out of it. Liars cast SO much better. Witnesses just... are.",
   "focused": "Contagion is documented - the 1973 wave began with two witnesses in Mississippi and propagated for months via media coverage. However, contagion models require an index case with genuine observation. The recurring index-case profile - agricultural workers, law enforcement, medical staff - is inconsistent with incentive-based fabrication. Fabricators optimize for audience; index cases consistently gain nothing.",
  }),
  ("c",
   "Man, you're good at this. Alright - the patient zero thing is a note I'll take. But I still say your show is a writers' room that doesn't know it's a writers' room.",
   "Man, you're good at this. Alright - the patient zero thing is, uh... that's a note I'll take. But I still say your show is a writers' room that doesn't know it's a writers' room."),
  ("v", {
   "neutral": "And I'll say yours is a writers' room that's never met a farmer at 3 AM. The line stays open for both of us - and if you ever sit in on a screening call, really sit in on one, I think you'd hear the one thing you can't put in a script. Thanks for calling. Keep writing.",
   "tired": "... and yours is a writers' room that's never met a farmer at 3 AM. line's open for both of us. sit in on a screening call sometime - really sit. you'd hear something you can't script. keep writing.",
   "irritated": "And yours is a writers' room that's never met a farmer at 3 AM. The line stays open for both of us. Sit in on a screening sometime - you'd hear something you can't script. Thanks for calling.",
   "gruff": "Yours is a writers' room that's never met a farmer at 3 AM. Line's open for both. Sit in on a screening sometime. Keep writing.",
   "amused": "Ha! And yours is a writers' room that's never met a farmer at 3 AM! The line stays open for both of us - and sit in on a screening call sometime, really sit, and I promise you'll hear the one thing you can't put in a script. Thanks for calling - keep writing!",
   "focused": "And your writers' room has never interviewed a farmer at 3 AM. The line remains open to both theses. I recommend direct observation of a screening call; the affect is not reproducible on the page. Thank you for calling.",
  }),
 ],
},
{
 "arcId": "ufo_starling_man",
 "legitimacy": "Fake",
 "gender": "male",
 "personality": "cold_factual",
 "summary": "Ornithology grad student lectures that ninety percent of sightings are starling murmurations",
 "notes": "Opinion caller, condescending, zero fieldwork on the residual cases (Fake). Vern concedes the top of the pile (Blue Book astronomical share), then holds the line on the hover/dual-radar/Belgian residual and mails him the hover file",
 "turns": [
  ("v", {
   "neutral": "You're on the air. You told the screener you can explain nine out of ten sightings without leaving your backyard. Go on.",
   "tired": "... you're on. nine out of ten from your backyard. go on.",
   "irritated": "You're on. Nine out of ten from your backyard - explain.",
   "gruff": "You're on. The backyard thing. Go.",
   "amused": "You're on the air and you've solved nine out of ten from a backyard! I love this show. Go on.",
   "focused": "You're on the air. You claim to resolve ninety percent of reports. State your mechanism.",
  }),
  ("c",
   "Starlings. Sturnus vulgaris. A murmuration at dusk - ten thousand birds moving as one body over a field, catching the last light. Every phone in the county films the same dark shape that pulses and changes direction instantly. Because it's birds. Birds do that. I've watched your callers describe my study subjects for twenty minutes.",
   "Starlings. Sturnus vulgaris. A murmuration at dusk - ten thousand birds moving as one body over a field, catching the last light. And every phone in the county films the same dark shape that, uh... pulses and changes direction instantly. Because it's birds. Birds do that. I've watched your callers describe my study subjects for, like, twenty minutes."),
  ("v", {
   "neutral": "Birds. Alright - and before I argue: what share of my calls do you actually think that covers? Because I keep a tally.",
   "tired": "... birds. alright. what share of my calls does that cover? i keep a tally.",
   "irritated": "Birds. Fine. What share of my calls does that cover - exactly? I keep a tally.",
   "gruff": "What share? I keep a tally.",
   "amused": "BIRDS! Ha! Alright, professor - what share of my calls do the birds cover? I keep a tally, and I'll read it to you.",
   "focused": "Specify the coverage claim. What proportion of reports do you attribute to murmuration? I maintain a tally.",
  }),
  ("c",
   "Ninety percent of the moving-lights reports, easy. Dusk, autumn, a rural county, a phone at thirty frames with a shaky hand - you've got a pulsing alien shape. And it's not close to the whole answer. Add Venus at twilight, add drones, add Jupiter, which apparently moves when you drive past it, and you're at ninety-five. Your five percent is where the real mystery lives, and you spend the whole show on it because it pays.",
   "Ninety percent of the moving-lights reports, easy. Dusk, autumn, a rural county, a phone at thirty frames with a shaky hand - you've got a pulsing alien shape. And it's not even close to the whole answer, man. Add Venus at twilight, add drones, add Jupiter, which apparently moves when you drive past it, and you're at ninety-five. Your five percent is where the real mystery lives, and you spend the whole show on it because, uh... because it pays."),
  ("v", {
   "neutral": "My tally says you're not wrong about the top of the pile - Blue Book closed about a quarter of its cases astronomical, and starlings were in that file before anybody filmed them. But here's the bottom of my pile, your five percent: things seen in daylight. Things holding still against the wind for forty minutes. Things two radars tracked at once. Birds don't hover silent over a warehouse at 2 AM - and the Belgian triangle in '89 had NATO radar and scrambled jets behind it. Explain the hover, and the rest is yours.",
   "tired": "... not wrong about the top of the pile. blue book closed a quarter of its cases astronomical, starlings were in those files before phones. but the bottom of the pile - your five percent? daylight. things holding still against wind for forty minutes. two radars at once. birds don't hover silent over a warehouse at 2 AM. belgian triangle had NATO radar and jets behind it. explain the hover. the rest is yours.",
   "irritated": "You're not wrong about the top of the pile - Blue Book closed a quarter of its cases astronomical. But your five percent? Daylight. Objects holding still in wind for forty minutes. Dual radar tracks. Birds don't hover silent over a warehouse at 2 AM, and the Belgian triangle had NATO radar and fighters scrambled. Explain the hover - then you can have the rest.",
   "gruff": "Not wrong about the top. Blue Book - quarter astronomical. But the five percent: daylight. Forty minutes holding against wind. Two radars. Belgian triangle, NATO radar, jets scrambled. Birds don't hover silent at 2 AM. Explain the hover, the rest is yours.",
   "amused": "Professor, you're not wrong about the top of the pile - Blue Book itself closed a quarter of its cases as astronomical, and starlings were in those files before phones existed! But your five percent - oh, your five percent! Daylight objects! Something holding dead still against the wind for forty minutes! Two radars tracking one target! Birds don't hover silent over a warehouse at 2 AM, and the Belgian triangle had NATO radar and scrambled jets behind it! Explain the hover, and the rest of the night is yours!",
   "focused": "Your upper bound is consistent with the record: Project Blue Book resolved roughly a quarter of cases as astronomical, with avian phenomena documented well before consumer video. The residual five percent contains daylight observations, stationary-hover targets in wind, and simultaneous multi-radar tracks. Murmuration cannot produce a silent 2 AM hover, and the 1989-90 Belgian triangle was tracked by NATO radar with interceptor scrambles. Account for the hover cases and the remainder is conceded.",
  }),
  ("c",
   "The hover... look, drones cover some of the hover. Quadcopters. And the Belgian thing could have been a stealth program - the shapes were right for it, triangles were in the air by then. You're moving the goalposts onto my field and calling it a mystery.",
   "The hover... look, drones cover some of the hover. Quadcopters. And the Belgian thing could have been a stealth program - the shapes were right for it, triangles were in the air by then. You're, uh... you're moving the goalposts onto my field and calling it a mystery."),
  ("v", {
   "neutral": "Drones are in my tally too - the modern callers say drone before I do. But drones buzz at forty feet, they fly twenty minutes on a charge, and they're registered. A silent triangle the size of a football field over a Belgian highway in '89 is not a quadcopter and was on nobody's flight plan - the FAA said so in writing when the Belgians asked. Come back with an answer that doesn't need a bigger bird.",
   "tired": "... drones are in the tally - callers say drone before i do these days. but drones buzz at forty feet, twenty minutes a charge, registered. a silent triangle the size of a football field over a highway in '89 isn't a quadcopter, wasn't on any flight plan - the faa said so in writing. come back with an answer that doesn't need a bigger bird.",
   "irritated": "Drones are in my tally - callers say drone before I do these days. But drones buzz at forty feet, fly twenty minutes a charge, and they're registered. A silent football-field triangle over a Belgian highway in '89 wasn't a quadcopter and wasn't on any flight plan - the FAA said so in writing. Bring me an answer that doesn't need a bigger bird.",
   "gruff": "Drones are in the tally. Callers say drone first now. But drones buzz, twenty minutes a charge, registered. Silent triangle over a highway in '89 - not a quadcopter, not on a flight plan. FAA said so in writing. Bring an answer that doesn't need a bigger bird.",
   "amused": "Ha - drones ARE in my tally, the modern callers say drone before I can! But professor: drones buzz at forty feet, they fly twenty minutes on a charge, and they're registered! A silent triangle the size of a football field over a Belgian highway in '89 is not a quadcopter and was on nobody's flight plan - the FAA put that in writing when the Belgians asked! Come back with an explanation that doesn't need a bigger bird!",
   "focused": "Drone attribution is already reflected in my tally; modern reporters volunteer it first. However: consumer rotors are audible at close range, endurance-limited to roughly twenty minutes, and subject to registration. The 1989 Belgian triangle - silent, large-format, highway-adjacent - matches none of these, and the FAA confirmed in writing to Belgian authorities that no US flight plan covered it. The residual requires an explanation not reducible to avian or hobbyist platforms.",
  }),
  ("c",
   "A bigger bird. That's... that's actually a fair line. I'm keeping that. Look - I still think nine out of ten of your callers watched my starlings. But the hover file - send me the hover file. I'll read it.",
   "A bigger bird. That's... that's actually a fair line. I'm keeping that. Look - I still think nine out of ten of your callers watched my starlings. But the hover file - uh, send me the hover file. I'll read it."),
  ("v", {
   "neutral": "It goes out tonight - every stationary-target case logged in ninety days. Read it with your eyes, not your thesis, and then call me back. A birder who reads a radar file is worth ten callers who watched a movie. Thanks for calling.",
   "tired": "... goes out tonight. every stationary-target case in ninety days. read it with your eyes, not your thesis. then call back. a birder who reads radar is worth ten movie-watchers.",
   "irritated": "It goes out - ninety days of stationary-target cases. Read it with your eyes, not your thesis, then call back. A birder who reads radar is worth ten movie-watchers. Thanks for calling.",
   "gruff": "Sending it. Ninety days of stationary targets. Eyes, not thesis. Call back after. A birder who reads radar beats ten movie-watchers.",
   "amused": "It's in the mail - ninety days of stationary-target cases, the whole hover file! Read it with your eyes, not your thesis, and then you call me back. A birder who reads a radar file is worth ten callers who watched a movie - and I'll take that trade any night!",
   "focused": "The hover file will be sent: all stationary-target reports logged within a ninety-day window. Review it empirically before responding. A field ornithologist who engages radar data is worth ten secondhand reporters. Thank you for calling.",
  }),
 ],
},
]
