# -*- coding: utf-8 -*-
# Batch 1 content: crazy stories complete + opinion wave 1.
ARCS = [
{
 "arcId": "ufo_returned_ring",
 "legitimacy": "Credible",
 "gender": "female",
 "personality": "emotional_wreck",
 "summary": "Elderly widow's engagement ring vanished during a 1979 missing-time episode - it reappeared on her nightstand last week, worn and cracked",
 "notes": "Crazy-but-sincere. Vern treats her with dignity, shares returned-object lore, gives real preservation protocol (bag, date, jeweler photos). Ends warm",
 "turns": [
  ("v", {
   "neutral": "You're on the air. You said there's something on your nightstand you need to tell somebody about.",
   "tired": "... you're on. something on your nightstand? alright. take your time.",
   "irritated": "You're on. Something on your nightstand. Go ahead.",
   "gruff": "You're on. The nightstand thing. Go.",
   "amused": "You're on the air - and you brought me a nightstand mystery. Alright, I'm listening. What's on it?",
   "focused": "You're on the air. Describe the object you mentioned during screening.",
  }),
  ("c",
   "It's my engagement ring. My husband gave it to me in 1962. In August of '79 I lost it - I lost four hours that night too, and the ring was gone off my finger. Last Tuesday I woke up and it was sitting on my nightstand. Same ring. Except the inscription inside is worn smooth now, and there's a crack in the stone that wasn't there before.",
   "It's, um... it's my engagement ring. My husband gave it to me in 1962. And in August of '79 I lost it - I mean, I lost four hours that night too, you know, and the ring was just... gone off my finger. And last Tuesday I woke up and it was - it was sitting on my nightstand. Same ring. Except the inscription inside is worn smooth now, and there's this crack in the stone that, um... that wasn't there before."),
  ("v", {
   "neutral": "Forty-six years gone, and it comes back worn. Who else knows about this?",
   "tired": "... forty-six years gone. comes back worn. who else knows?",
   "irritated": "So it comes back after forty-six years, aged. Who else have you told?",
   "gruff": "Forty-six years. Worn. Who else knows?",
   "amused": "Forty-six years and it comes back looking like it's had adventures. Tell me - who else have you shown it to?",
   "focused": "A returned object showing decades of wear. Who else is aware?",
  }),
  ("c",
   "Nobody. My Harold passed in '09 - he never believed the lost hours, he thought I dropped it in the garden. The kids would look at me a certain way and I couldn't bear it. You're the first person I've told. That's why I'm calling a radio station at one in the morning, isn't it.",
   "Nobody. My Harold passed in '09 - he never believed the lost hours, he thought I'd dropped it in the garden. And the kids would just... look at me a certain way, and I couldn't bear it. You're the first person I've told. That's why I'm calling a radio station at, uh... at one in the morning, isn't it."),
  ("v", {
   "neutral": "You're not the first, and it isn't silly. Returned-object reports go back decades - things coming home with wear nobody can account for. Here's what I tell all of them: don't polish it, don't wear it. Bag it, date the bag, and have a jeweler photograph that inscription under magnification. The wear is the story.",
   "tired": "... you're not the first. returned objects go back decades - wear nobody can account for. don't polish it. bag it, date it, have a jeweler photograph the inscription under magnification. the wear is the story...",
   "irritated": "You're not the first - returned objects go back decades. Don't polish it, don't wear it. Bag it, date it, photograph the inscription under magnification. The wear is the evidence.",
   "gruff": "Not the first. Don't polish it. Bag it, date it, jeweler photographs the inscription. The wear's the story.",
   "amused": "You're not the first, and I mean that kindly - returned objects go back decades! And here's the fun part: don't polish it, don't wear it. Bag it, date it, get a jeweler to photograph that inscription. The wear IS the story.",
   "focused": "Returned-object reports span decades, typically with unaccounted wear. Protocol: no polishing, no wearing. Seal in a bag with the date. Have a jeweler photograph the inscription under magnification - the wear pattern is the data.",
  }),
  ("c",
   "The wear is the story... Lord. I've been staring at that crack for four nights. What does it mean, Vern? If it came back like that - where has it been?",
   "The wear is the story... Lord. I've been staring at that crack for four nights now. What does it mean, Vern? If it came back like that - where has it... where has it been?"),
  ("v", {
   "neutral": "It means it went somewhere that time passes. I can't tell you where - and anybody who can is selling something. But you've got a dated disappearance, Harold's journal entry from that night, and an object that came home with forty-six years of wear on it. That's a better file than most callers ever bring me.",
   "tired": "... means it went somewhere time passes. can't tell you where - nobody honest can. but the disappearance is dated, harold wrote it down, and the ring came home old. that's a better file than most...",
   "irritated": "It means somewhere time passes. I can't tell you where, and anyone who can is selling something. But a dated disappearance, Harold's journal, and a ring that came home aged - that's a real file.",
   "gruff": "Went somewhere time passes. Can't say where - nobody honest can. Dated disappearance, Harold's journal, ring came home old. That's a file.",
   "amused": "It means your ring went somewhere the years still tick! Can't tell you where - anybody who claims they can is selling something. But a dated disappearance, Harold's own journal, and jewelry that came home with forty-six years on it? That's a file I'd read twice.",
   "focused": "The wear implies elapsed time in storage or transit. Location is unknowable - treat anyone claiming otherwise as a salesman. What you have: a dated disappearance, a contemporaneous journal entry, and an object with forty-six years of unaccounted wear. That is an above-average case file.",
  }),
  ("c",
   "Thank you. I think I needed to hear somebody say that out loud without laughing. Harold would have laughed - and then he'd have made me cocoa. Can I call you back? Can I tell you what the jeweler says?",
   "Thank you. I think I, um... I needed to hear somebody say that out loud without laughing. Harold would have laughed - and then he'd have made me cocoa. Can I call you back? Can I tell you what the jeweler says?"),
  ("v", {
   "neutral": "You call this line any hour and tell me what the jeweler says - and when you bag it, write the date in pen, not pencil. You carried that ring and that story for forty-six years with nobody to tell. You've got somebody now. Go bag your ring. Goodnight.",
   "tired": "... call any hour. tell me what the jeweler says. bag it, date it in pen. forty-six years you carried this alone... you've got a line now. goodnight.",
   "irritated": "Call back any hour with what the jeweler says. Bag it, date it in pen. Forty-six years alone with this - you've got a line now. Goodnight.",
   "gruff": "Call back. Jeweler's verdict. Bag it, date it, pen not pencil. Goodnight.",
   "amused": "You call this line any hour of the night - you've earned the direct number! Tell me what the jeweler says, and bag it with the date in pen, not pencil - we're running an investigation, not a lemonade stand! Goodnight!",
   "focused": "Report back through this line when the jeweler's assessment is complete. Bag the ring, date the bag in pen. For the record: you carried this alone for forty-six years - it is documented now. Goodnight.",
  }),
 ],
},
{
 "arcId": "ufo_wedding_lights",
 "legitimacy": "Questionable",
 "gender": "male",
 "personality": "charismatic_storyteller",
 "summary": "Man tells the story of the amber ring of light that reconciled him and his wife at the old fairground - and came back on three anniversaries since",
 "notes": "Crazy-but-charming, half-in-on-it. Vern gives the honest mundane reading (lanterns/towers, anniversary-lights calls since '98) but concedes the part that matters. Warm close",
 "turns": [
  ("v", {
   "neutral": "You're on the air. You told the screener this is an anniversary story. Whose anniversary?",
   "tired": "... you're on. an anniversary story? whose?",
   "irritated": "You're on. Anniversary of what, exactly?",
   "gruff": "You're on. Whose anniversary?",
   "amused": "You're on the air with an anniversary story! Now I want to hear this one. Whose?",
   "focused": "You're on the air. You called about an anniversary. Specify the event.",
  }),
  ("c",
   "Mine and my wife's - sort of. Eleven years ago we were done. Boxes packed, the whole sad routine. Night before I was supposed to drive to Cleveland for good, I pulled into the old fairground where we had our first date, just to say goodbye to it. And the lights came up over the Ferris wheel.",
   "Mine and my wife's - sort of. Eleven years ago we were done. Boxes packed, the whole, uh... the whole sad routine. And the night before I was supposed to drive to Cleveland for good, I pulled into the old fairground where we had our first date, just to, you know, say goodbye to it. And the lights came up over the Ferris wheel."),
  ("v", {
   "neutral": "Lights. What kind of lights - and take your time with this.",
   "tired": "... what kind of lights? take your time.",
   "irritated": "What kind of lights? Be exact.",
   "gruff": "What kind?",
   "amused": "Lights over the Ferris wheel on goodbye night! Of course there were. What kind of lights?",
   "focused": "Describe them. Color, count, motion.",
  }),
  ("c",
   "Three of them, amber, moving slow - and I know how that sounds, I've had eleven years to hear it all. They came together over the wheel and they made a circle. Just hung there, a ring of light, maybe a minute. And she was there too - we'd both gone to the fairground, separately, don't ask me how. She was by the ticket booth and she said: is that your idea? And I said no. And then I asked her to marry me, right there, under it.",
   "Three of them, amber, moving slow - and I know how that sounds, I've had eleven years to, uh... to hear it all. They came together over the wheel and they made a circle. Just hung there, a ring of light, maybe a minute. And she was there too - we'd both gone to the fairground, separately, don't ask me how. She was by the ticket booth and she goes, 'is that your idea?' And I said no. And then I, um... I asked her to marry me. Right there, under it."),
  ("v", {
   "neutral": "You proposed under an amber ring neither of you can explain. Eleven years on - you still think about that minute?",
   "tired": "... proposed under a ring of light neither of you can explain. eleven years on. you still think about that minute?",
   "irritated": "So you proposed under lights nobody can explain. Eleven years later - what's the story now?",
   "gruff": "Proposed under lights nobody can explain. Eleven years. Still thinking about it?",
   "amused": "A man proposes under an unexplained ring of light and it works! Eleven years! Do you still think about that minute?",
   "focused": "An unexplained aerial formation coincided with a reconciliation. Eleven years later - how do you interpret that minute now?",
  }),
  ("c",
   "Every year. And here's what gets me - three anniversaries running, we've been out there, and the same three lights came up over the wheel. Same time, near as we can tell. We don't say anything. We just watch. Then we go get pie.",
   "Every year. And here's what gets me - three anniversaries running, we've been out there, and the same three lights came up over the wheel. Same time, near as we can tell. We don't, uh... we don't say anything. We just watch. Then we go get pie."),
  ("v", {
   "neutral": "Here's the honest reading, because you can take it: three amber lights over a fairground could be lanterns, could be drones, could be a tower. I've logged every anniversary-lights call since '98 and most of them end mundane. What doesn't end mundane is two people driving to the same fairground the same night, separately, and a marriage that started under it. The ring on her hand out-argues anything in the sky. Keep going for pie.",
   "tired": "... honest reading? three lights could be lanterns, could be a tower. been logging anniversary-lights calls since '98, most end mundane. what doesn't end mundane is the two of you being there that night, separately. and eleven years since. the ring on her hand out-argues the sky. keep the pie...",
   "irritated": "Honest reading: amber lights over a fairground - lanterns, drones, a tower, take your pick. I've had those calls since '98 and they mostly end mundane. What's not mundane is the two of you being there that night separately, and the eleven years since. Keep going for pie.",
   "gruff": "Honest reading: could be lanterns, could be a tower. Had those calls since '98. Mostly mundane. The two of you being there that night, separately - that part isn't. Keep the pie tradition.",
   "amused": "Alright, honest reading from a man who's heard it all: three amber lights could be lanterns, drones, or a tower having a night! I've logged anniversary-lights calls since '98 and most end with somebody sheepish. But two hearts pulling into the same fairground the same night? That's the part I can't debunk. Keep going for pie!",
   "focused": "Honest analysis: three amber lights over a fairground are consistent with lanterns, drones, or tower beacons - I've logged anniversary-lights reports since 1998 and the majority resolve mundanely. What resists mundane analysis: two parties independently present at the same site the same night, and an eleven-year stable outcome. The terrestrial ring outweighs the aerial one.",
  }),
  ("c",
   "Ha! That's the best answer anybody's given me. My brother says I married a weather balloon. I'm going to tell him the ring on her hand out-argues the sky.",
   "Ha! That's the best answer anybody's given me. My brother says I married a weather balloon. I'm gonna tell him the ring on her hand, uh... out-argues the sky."),
  ("v", {
   "neutral": "You tell him that, and you tell him Vern said so. Eleven years, three lights, one pie - best file I've had all week, and I'm counting the ones with radar. Happy anniversary. Thanks for calling.",
   "tired": "... tell him vern said so. eleven years, three lights, one pie. best file i've had all week, and i'm counting the radar ones. happy anniversary.",
   "irritated": "Tell him Vern said so. Eleven years, three lights, pie. Best file all week - and yes, I'm counting the radar ones. Happy anniversary. Thanks for calling.",
   "gruff": "Tell him Vern said so. Happy anniversary. Thanks for calling.",
   "amused": "You tell your brother the ring out-argues the sky, and that Vern agrees! Eleven years, three lights, and pie - best file I've had all week, radar included! Happy anniversary to you both!",
   "focused": "Relay the analysis to your brother. Eleven years, three light events, stable outcome - the strongest file of the week, radar cases included. Happy anniversary. Thank you for calling.",
  }),
 ],
},
{
 "arcId": "ufo_alien_jury",
 "legitimacy": "Questionable",
 "gender": "male",
 "personality": "nervous_hesitant",
 "summary": "Man believes he was drafted as a juror in some proceeding over his neighbor's back forty - woke at 4 AM in his lawn chair, certain he'd voted not guilty",
 "notes": "Crazy-but-sincere, apologetic hedger. Vern shares participant-role literature (juror/nurse/interpreter), gives documentation protocol, files his grievance on air. Kind close",
 "turns": [
  ("v", {
   "neutral": "You're on the air. The screener wrote down 'jury duty' - which, at this hour, I assume is not the county's.",
   "tired": "... you're on. jury duty? at this hour? that's not the county's, is it.",
   "irritated": "You're on. Jury duty. Explain why you're calling a UFO line about jury duty.",
   "gruff": "You're on. Jury duty. Not the county's?",
   "amused": "You're on the air with a jury duty story - on THIS line! Alright, you have my attention. Whose court?",
   "focused": "You're on the air. You reported jury duty through our UFO screening line. Clarify.",
  }),
  ("c",
   "I know how it sounds. I almost hung up on your screener myself. It's about my neighbor - we don't get along, property line, twenty years of it. Two weeks back I was on my porch after supper, and there was this light over his back forty, low and steady. Next thing I actually remember is four in the morning, sitting in my lawn chair in my own yard, shoes on wrong, and this... this complete certainty that I had just voted not guilty.",
   "I know how it sounds. I almost hung up on your screener myself. It's about my neighbor - we don't get along, property line, twenty years of it. Two weeks back I was on my porch after supper, and there was this light over his back forty, low and, uh... steady. And the next thing I actually remember is four in the morning, sitting in my lawn chair in my own yard, shoes on wrong, and this... this complete certainty that I had just voted not guilty."),
  ("v", {
   "neutral": "You voted not guilty. On what? And before you say you don't know - sit with the question a second.",
   "tired": "... voted not guilty. on what? sit with that a second before you say you don't know.",
   "irritated": "You voted not guilty - on what? Don't tell me you don't know. Think.",
   "gruff": "Not guilty of what?",
   "amused": "A not-guilty vote at four in the morning, in the wrong shoes! Alright - voted on what? Sit with it.",
   "focused": "You report certainty of a verdict. Verdicts require charges. What were you voting on?",
  }),
  ("c",
   "That's the thing - I don't have words for it. It wasn't words, it was knowing. Like knowing somebody's lying without hearing the lie. The knowing was about my neighbor. And whatever it was they were laying on him, I voted that it wasn't so. I've thought about it every day since. I don't know the charge, I don't know who else was on that jury, and I need to know if that makes me a witness or a lunatic.",
   "That's the thing - I don't have words for it. It wasn't words, it was... knowing. Like knowing somebody's lying without hearing the lie. The knowing was about my neighbor. And whatever it was they were laying on him, I voted that it wasn't so. I've thought about it every day since. I don't know the charge, I don't know who else was on that jury, and I, uh... I need to know if that makes me a witness or a lunatic."),
  ("v", {
   "neutral": "It makes you a reporter - the only one of those that ever gets anywhere. The case literature goes back to the eighties, and participants show up in it: people who come back with roles. Juror. Nurse. Interpreter. The role is the detail nobody invents, because it doesn't match the movies. Write the knowing down nightly while it's fresh. Note the chair, the shoes, the gap. Don't go onto his forty. And your grievance about being taken off your own porch? You just filed it. On the record, with a hundred thousand ears.",
   "tired": "... a reporter. that's the one that gets somewhere. the books have had participants since the eighties - people coming back with roles. juror. nurse. the role's the detail nobody invents, it doesn't match the movies. write the knowing down nightly. note the chair, the shoes, the gap. stay off his forty. and your grievance? just filed it. on the record...",
   "irritated": "A reporter - the only useful one of the three. Participant cases go back to the eighties; people come back with roles - juror, nurse, interpreter. The role's the part nobody invents, it doesn't match the movies. Write the knowing down nightly, note the chair, the shoes, the gap. Stay off his property. And your grievance about the porch? You just filed it, on the record.",
   "gruff": "Reporter. Only useful one. Participant cases since the eighties - jury, nurse, interpreter. The role's the part nobody invents. Write it down nightly. Chair, shoes, gap. Stay off his forty. Grievance's filed. On the record.",
   "amused": "A reporter! The only one of those that gets invited back! You know, the case books have had participants since the eighties - folks coming home with roles: juror, nurse, interpreter. The role's the tell nobody invents, because it doesn't match the movies at all. Write that knowing down every night. Note the chair, the shoes, the gap. Stay off his forty - and as for your grievance? Consider it filed, on the record, with applause.",
   "focused": "Classification: reporter. Participant-role cases are documented since the 1980s - subjects returning with functions: juror, medic, interpreter. The role is the non-fabricated detail; it contradicts media templates. Protocol: nightly written recall while fresh, document the chair, footwear, and time gap. Do not trespass his property. Your complaint is now entered on the broadcast record.",
  }),
  ("c",
   "On the record... yeah. Yeah, okay. Can I ask you something dumb? Do you think they'll call me back? Because part of me - the part that doesn't sleep - part of me hopes they don't.",
   "On the record... yeah. Yeah, okay. Can I ask you something dumb? Do you think they'll, um... they'll call me back? Because part of me - the part that doesn't sleep - part of me hopes they don't."),
  ("v", {
   "neutral": "That's not a dumb question, it's the right one, and the honest answer is that files like yours go both ways. Some never hear another thing. Some get the knock years later. The books are split and so am I. Keep the nightly notes either way - if they come back, you'll have the record; if they don't, you'll have proof a man kept faith with the truth. And sleep. The porch light can stay on. That's not cowardice, that's a man marking his property.",
   "tired": "... right question. files like yours go both ways - some never hear again, some get the knock years later. books are split, so am i. keep the notes either way. and sleep. porch light on - that's not cowardice, that's marking your property...",
   "irritated": "Not dumb - it's the right question, and files like yours go both ways. Some never hear again. Some get the knock years later. The books are split; so am I. Keep the notes either way. Sleep. And leave the porch light on - that's not cowardice, that's marking your property.",
   "gruff": "Right question. Files like yours go both ways. Some never hear again, some do, years later. Books are split. Keep the notes either way. Sleep. Porch light on - marking your property, not cowardice.",
   "amused": "Not dumb - it's THE question, and the honest answer is files like yours go both ways! Some never hear a peep again. Some get the knock twenty years later, right when they've stopped flinching. The books are split and so am I - you're in excellent company! Keep the notes either way. And sleep with the porch light on - that's not cowardice, that's a man marking his property!",
   "focused": "Valid question. Outcome distribution for participant cases is bimodal: no further contact, or delayed recontact after years. The literature disagrees and so do I. Maintain nightly documentation under either outcome - it is your record if they return, and your proof of rigor if they don't. Prioritize sleep. The porch light is a property marker, not a fear response.",
  }),
  ("c",
   "Marking my property. I like that. I'm going to write that one down too - in the notebook, right under 'not guilty.' Thank you, Vern. I think that's the first time I've said the whole thing out loud and somebody didn't hang up on me.",
   "Marking my property. I like that. I'm gonna write that one down too - in the notebook, right under, uh... 'not guilty.' Thank you, Vern. I think that's the first time I've said the whole thing out loud and somebody didn't hang up on me."),
  ("v", {
   "neutral": "Nobody's hanging up. The notebook gets 'not guilty,' it gets 'marking my property,' and it gets tonight's date - because that's the night you said it out loud. If they ever do call you back, this line already knows your name. Sleep well, juror. Thanks for calling.",
   "tired": "... nobody's hanging up. notebook gets 'not guilty,' gets 'marking my property,' gets tonight's date - the night you said it out loud. if they call back, this line knows your name. sleep, juror.",
   "irritated": "Nobody's hanging up. 'Not guilty,' 'marking my property,' tonight's date - in the book. If they call back, this line knows your name already. Sleep, juror. Thanks for calling.",
   "gruff": "Nobody hangs up here. Both phrases in the book, tonight's date. Line knows your name if they call back. Sleep, juror.",
   "amused": "Nobody's hanging up on YOU - best story of the night! Both phrases in the notebook, tonight's date, because that's the night the juror spoke! And if they ever call you back? This line already knows your name. Sleep well, counselor!",
   "focused": "No disconnection will occur. Enter both phrases with tonight's date - the date of first full disclosure. Should recontact occur, this broadcast holds a contemporaneous record. Rest now. Thank you for calling.",
  }),
 ],
},
]
