# -*- coding: utf-8 -*-
# Batch 4 content (part 1): opinion wave 4.
ARCS = [
{
 "arcId": "ufo_shoot_it_down",
 "legitimacy": "Questionable",
 "gender": "male",
 "personality": "gruff_experienced",
 "summary": "Retired Air Force man: shoot one down, reverse-engineer it publicly - the games end in an afternoon",
 "notes": "Opinion caller with real service history. Vern counters with the intercept record ('52 Washington, 2004 Tic Tac outmaneuvering F/A-18s) and the debris-risk argument. Concedes the corral is radar, not guns",
 "turns": [
  ("v", {
   "neutral": "You're on the air. You told the screener you have one recommendation for the United States Air Force. Go ahead.",
   "tired": "... you're on. one recommendation for the air force. go ahead.",
   "irritated": "You're on. One recommendation for the Air Force. Go.",
   "gruff": "You're on. The recommendation. Go.",
   "amused": "You're on the air with advice for the entire Air Force! Alright - I'm listening. Go ahead.",
   "focused": "You're on the air. You have a policy recommendation for the Air Force. State it.",
  }),
  ("c",
   "Twenty-two years Air Force, eleven in interceptors. Here's the recommendation: shoot one down. Catch the wreckage, put the engineers on it in public, and let the whole world watch the analysis. Seventy years of hide-and-seek could have ended in one afternoon in 1952 over Washington, and it could still end next Tuesday if anybody had the spine to order it.",
   "Twenty-two years Air Force, eleven in interceptors. Here's the recommendation: shoot one down. Catch the wreckage, put the engineers on it in public, and let the whole world watch the analysis. Seventy years of, uh... of hide-and-seek could have ended in one afternoon in 1952 over Washington, and it could still end next Tuesday if anybody had the spine to order it, man."),
  ("v", {
   "neutral": "1952 over Washington - that's exactly where your argument starts, so let's finish it. Do you know what happened when the interceptors actually scrambled?",
   "tired": "... 1952 over washington - that's where your argument starts, so let's finish it. you know what happened when the interceptors actually scrambled?",
   "irritated": "1952 over Washington - that's where your own argument starts, so let's finish it. What happened when the interceptors actually scrambled?",
   "gruff": "'52 over Washington. Your argument starts there. What happened when the interceptors scrambled?",
   "amused": "1952 over Washington - ha, that's exactly where your argument starts, so let's finish it together! What happened when the interceptors actually scrambled?",
   "focused": "1952, Washington - the origin case for your recommendation. Establish the outcome: what occurred when interceptors scrambled?",
  }),
  ("c",
   "Chased lights for three weekends. Never closed on a thing, and when the radars lost them the jets were left burning fuel at empty sky. And - and I know how that sounds. It sounds like the argument for shooting sooner, while you still have the angle.",
   "Chased lights for three weekends. Never closed on a thing, and when the radars lost them the jets were left burning fuel at empty sky. And - and I know how that sounds, Vern. It sounds like the argument for shooting sooner, while you still have the angle, you know?"),
  ("v", {
   "neutral": "It sounds like an argument that hasn't met the 2004 file. Off San Diego, Navy F/A-18s - the best pilots and the best sensors on the planet - found the famous tic-tac, and it ran circles around them, dove into the ocean, and was gone before anyone could get a firing solution. The military has been trying to catch these since before you were flying. Here's the whole doctrine in one sentence: you don't shoot down what you can't catch - and what you can catch is usually explainable.",
   "tired": "... it's an argument that hasn't met the 2004 file. off san diego, navy f/a-18s - best pilots, best sensors on the planet - found the tic-tac. it ran circles around them, dove into the ocean, gone before anybody had a firing solution. the military's been trying to catch these since before you were flying. whole doctrine in one sentence: you don't shoot down what you can't catch... and what you can catch is usually explainable.",
   "irritated": "It's an argument that hasn't met the 2004 file. Off San Diego - Navy F/A-18s, best pilots and sensors on the planet - found the tic-tac. It ran circles around them, dove into the ocean, gone before anyone had a firing solution. The military has been trying to catch these since before you were flying. The whole doctrine in one sentence: you don't shoot down what you can't catch, and what you can catch is usually explainable.",
   "gruff": "Argument hasn't met the 2004 file. Off San Diego - Navy F/A-18s, best pilots and sensors on the planet, found the tic-tac. Ran circles, dove into the ocean, gone before a firing solution. Military's tried catching these since before you flew. One sentence: don't shoot what you can't catch - and what you can catch usually explains.",
   "amused": "Ha - it sounds like an argument that hasn't met the 2004 file! Off San Diego, Navy F/A-18s - the best pilots and the best sensors on the planet - found the famous tic-tac! And it ran CIRCLES around them, dove into the ocean, and was gone before anybody got a firing solution! The military has been trying to catch these since before you were flying, my friend! Here's the whole doctrine in one sentence: you don't shoot down what you can't catch - and what you CAN catch is usually explainable!",
   "focused": "That position does not survive the 2004 San Diego engagement: Navy F/A-18s with premier aircrew and sensor suites acquired the tic-tac target, which demonstrated instantaneous acceleration, trans-medium transit, and evasion beyond engagement envelope. Intercept attempts span seven decades. The operative doctrine reduces to one sentence: engagement requires catchability, and catchable targets are predominantly explicable.",
  }),
  ("c",
   "So your answer is to wait for it to slow down. That's a coward's doctrine, Vern. Deterrence means the sky over this country has a price, and right now the price is zero.",
   "So your answer is to wait for it to slow down. That's a coward's doctrine, Vern. Deterrence means the sky over this country has a price, and right now the, uh... the price is zero, man."),
  ("v", {
   "neutral": "Deterrence means knowing what you're deterring - and here's the other half of your afternoon in 1952. Unknown propulsion means unknown wreckage. You shoot down something flying physics you can't name, and what lands isn't a laboratory. It might be a crater. It might be a material nobody can handle. It might be an incident that starts a war, because every other country sees a missile fired at something they've seen too. Every general who thinks about this for five minutes lands in the same place: capture the data, not the target. The shooting part's easy. Living with what comes down is the hard part.",
   "tired": "... deterrence means knowing what you're deterring. and here's the other half of your afternoon in 1952. unknown propulsion means unknown wreckage. you shoot down something flying physics you can't name, and what lands isn't a laboratory. might be a crater. might be material nobody can handle. might be an incident that starts a war, because every other country sees a missile fired at something they've seen too. every general who thinks five minutes lands in the same place: capture the data, not the target. shooting's easy. living with what comes down is the hard part.",
   "irritated": "Deterrence means knowing what you're deterring. Here's the other half of your 1952 afternoon: unknown propulsion means unknown wreckage. You shoot down something flying physics you can't name and what lands isn't a laboratory - it might be a crater, a material nobody can handle, or an incident that starts a war, because every other country sees a missile fired at something they've seen too. Every general who thinks five minutes lands in the same place: capture the data, not the target. Shooting's easy. Living with what comes down is the hard part.",
   "gruff": "Deterrence means knowing what you're deterring. Other half of your '52 afternoon: unknown propulsion, unknown wreckage. Shoot down something flying physics you can't name - what lands isn't a lab. Might be a crater. Material nobody can handle. An incident that starts a war, because every other country's seen the same thing. Every general who thinks five minutes lands in one place: capture the data, not the target. Shooting's easy. Living with what comes down is hard.",
   "amused": "Deterrence means knowing what you're DETERRING - and here's the other half of your afternoon in 1952! Unknown propulsion means unknown wreckage! You shoot down something flying physics you can't name, and what lands isn't a laboratory - it might be a crater! It might be a material nobody can handle! It might be an incident that starts a war, because every other country sees a missile fired at something they've seen too! Every general who thinks about this for five minutes lands in the same place: capture the data, not the target! The shooting part's easy, my friend - living with what comes down is the hard part!",
   "focused": "Deterrence presupposes a known adversary. The second half of your 1952 scenario: unknown propulsion implies unknown wreckage composition. Downed material could constitute a crater-scale hazard, an unhandleable substance, or an international incident - every foreign observer having witnessed comparable phenomena. Informed command converges on one doctrine: acquire data, not the target. Engagement is trivial; consequence management is not.",
  }),
  ("c",
   "Living with what comes down... alright, I'll grant that part. I still say a country that can put a man on the moon ought to be able to corral one of those things. But I'll grant the crater math.",
   "Living with what comes down... alright, I'll grant that part, Vern. I still say a country that can put a man on the moon ought to be able to corral one of those things. But I'll, uh... I'll grant the crater math."),
  ("v", {
   "neutral": "Maybe it can corral one - and the day it does, this show plays the tapes for a week. Until then, the corral is radar, and we're building it: every track, every gun camera, every sworn pilot adds another rail. That's the shoot-down that works, captain. It just takes a country instead of a missile. Thanks for calling.",
   "tired": "... maybe it can corral one. and the day it does, this show plays the tapes for a week. until then, the corral is radar, and we're building it: every track, every gun camera, every sworn pilot adds a rail. that's the shoot-down that works. takes a country instead of a missile.",
   "irritated": "Maybe it can corral one - and the day it does, this show plays the tapes for a week. Until then, the corral is radar, and we're building it: every track, every gun camera, every sworn pilot adds another rail. That's the shoot-down that works. It takes a country instead of a missile. Thanks for calling.",
   "gruff": "Maybe it can corral one. Day it does, this show plays tapes for a week. Till then the corral's radar, and we're building it - every track, gun camera, sworn pilot, another rail. Shoot-down that works. Takes a country, not a missile.",
   "amused": "Maybe it CAN corral one - and the day it does, this show plays the tapes for a week straight! Until then, the corral is radar, and we're building it: every track, every gun camera, every sworn pilot adds another rail! That's the shoot-down that works, captain - it just takes a country instead of a missile! Thanks for calling!",
   "focused": "Corral capability may yet arrive; when it does, this program will broadcast the documentation continuously. Meanwhile the corral is sensor-based and under construction: each radar track, gun camera file, and sworn aviator report adds a rail. That is the functional shoot-down - national in scale rather than kinetic. Thank you for calling.",
  }),
 ],
},
{
 "arcId": "ufo_ready_for_contact",
 "legitimacy": "Questionable",
 "gender": "female",
 "personality": "enthusiastic_convert",
 "summary": "Caller wants the station to broadcast a nightly welcome message - 'we're ready'",
 "notes": "Opinion caller, warm and sincere. Vern shares Arecibo 1974 + the METI transmission debate + the century of accidental leakage, concedes her side half-wins, reframes readiness as not sounding scared. Hopeful close",
 "turns": [
  ("v", {
   "neutral": "You're on the air. You told the screener you have a programming request - for every night. Go ahead.",
   "tired": "... you're on. a programming request. for every night. go ahead.",
   "irritated": "You're on. A programming request for every night. Go.",
   "gruff": "You're on. Every-night request. Go.",
   "amused": "You're on the air with a programming request - for EVERY night! Bold. I like bold. Go ahead.",
   "focused": "You're on the air. You have a recurring programming proposal. State it.",
  }),
  ("c",
   "I've listened three years, and I want to say what nobody on this show will say: we're ready. Not the governments - people. Kids don't flinch at the sky anymore. So do the thing radio is actually for - broadcast a welcome. Every night, same time, one message: you are not alone, and neither are we.",
   "I've listened three years, and I want to say what nobody on this show will say: we're ready. Not the governments - people, man. Kids don't flinch at the sky anymore. So do the thing radio is actually for - broadcast a welcome. Every night, same time, one message: you are not alone, and neither are we, you know?"),
  ("v", {
   "neutral": "A welcome broadcast. Do you know somebody's actually tried that - do you know what happened the first time?",
   "tired": "... a welcome broadcast. you know somebody's actually tried that? what happened the first time?",
   "irritated": "A welcome broadcast. Somebody's actually tried that. You know what happened the first time?",
   "gruff": "Welcome broadcast. Somebody tried it. Know what happened?",
   "amused": "A welcome broadcast! Ha - do you know somebody's actually TRIED that? Do you know what happened the first time?",
   "focused": "A welcome transmission. Precedent exists. Are you familiar with the first attempt?",
  }),
  ("c",
   "Arecibo! 1974! I know it - they beamed at a star cluster, sixteen hundred and seventy-nine pulses, prime numbers, DNA, the whole thing. But Vern, that was scientists saying hello to mathematics. I'm talking about people saying hello to people. There's a difference.",
   "Arecibo! 1974! I know it - they beamed at a star cluster, sixteen hundred and seventy-nine pulses, prime numbers, DNA, the whole thing. But Vern, that was scientists saying hello to mathematics, man. I'm talking about people saying hello to people. There's, uh... there's a difference."),
  ("v", {
   "neutral": "There is a difference - and there's a fight about it too. The people who run the big dishes have argued for thirty years over whether to transmit at all: half call silence caution, half call it cowardice. And here's what neither side says on the air: we've been leaking a hello for a century anyway. Radio, television, radar - every broadcast since the thirties expanding outward at light speed. The welcome already left the building. We just never got to vote on it.",
   "tired": "... there is a difference - and a fight about it. the people who run the big dishes have argued thirty years over whether to transmit at all. half call silence caution, half call it cowardice. and what neither side says: we've been leaking a hello for a century anyway. radio, television, radar - every broadcast since the thirties expanding at light speed. the welcome already left the building... we just never got to vote on it.",
   "irritated": "There IS a difference - and a fight about it. The people who run the big dishes have argued thirty years over whether to transmit at all. Half call silence caution, half call it cowardice. And what neither side says on the air: we've been leaking a hello for a century anyway. Radio, television, radar - every broadcast since the thirties expanding at light speed. The welcome already left the building. We just never voted on it.",
   "gruff": "There's a difference - and a fight. Big-dish people have argued thirty years over transmitting at all. Half call silence caution, half cowardice. Neither says this: we've leaked a hello for a century anyway. Radio, TV, radar - every broadcast since the thirties, expanding at light speed. Welcome left the building. Nobody voted on it.",
   "amused": "There IS a difference - and there's a FIGHT about it! The people who run the big dishes have been arguing for thirty years over whether to transmit at all - half call silence caution, half call it cowardice! And here's what neither side says on the air: we've been leaking a hello for a CENTURY anyway! Radio! Television! Radar! Every broadcast since the thirties, expanding outward at light speed! The welcome already left the building, my friend - we just never got to vote on it!",
   "focused": "The distinction is real, and contested: the active-transmission debate has run thirty years among radio astronomers - silence framed as prudence versus silence framed as timidity. The omitted variable: a century of unintentional leakage. Broadcast television, radio, and radar emissions have propagated at light speed since the 1930s. The greeting has already transmitted; the vote never occurred.",
  }),
  ("c",
   "It already left the building... Vern, you realize that's my side, right? If the hello's already gone, the only question left is whether we're rude when they answer.",
   "It already left the building... Vern, you realize that's my side, right? If the hello's already gone, the only question left is whether we're, uh... whether we're rude when they answer, man."),
  ("v", {
   "neutral": "You'd make me argue against myself on my own show - and you nearly have. But I'll say the other half too, because somebody should: readiness isn't a vote, and a welcome from this frequency reaches one county, not one species. When the sky gives us something two radars agree on, that's when the world says hello - in one voice, not two hundred. Until then, what this line can do is make sure nobody sounds afraid when that day comes. That's a kind of welcome too. Keep listening. And keep asking.",
   "tired": "... you'd make me argue against myself on my own show - and you nearly have. but the other half, because somebody should: readiness isn't a vote. a welcome from this frequency reaches one county, not one species. when the sky gives us something two radars agree on, that's when the world says hello - one voice, not two hundred. until then, this line makes sure nobody sounds afraid when that day comes. that's a kind of welcome too. keep listening... keep asking.",
   "irritated": "You'd make me argue against myself on my own show - and you nearly have. The other half, because somebody should say it: readiness isn't a vote, and a welcome from this frequency reaches one county, not one species. When the sky gives us something two radars agree on, THAT's when the world says hello - one voice, not two hundred. Until then, this line makes sure nobody sounds afraid when the day comes. That's a kind of welcome too.",
   "gruff": "You'd make me argue against myself - nearly succeeded. Other half: readiness isn't a vote. Welcome from this frequency reaches one county, not one species. Sky gives something two radars agree on - that's when the world says hello. One voice, not two hundred. Till then, this line makes sure nobody sounds afraid. That's welcome too. Keep listening.",
   "amused": "Ha - you'd make me argue against myself on my own show, and you NEARLY have! But the other half, because somebody should say it: readiness isn't a vote! A welcome from this frequency reaches one county, not one species! When the sky gives us something two radars agree on, THAT's when the world says hello - in one voice, not two hundred! Until then, what this line can do is make sure nobody sounds afraid when that day comes! That's a kind of welcome too! Keep listening - and keep asking!",
   "focused": "You nearly turned me into my own opposition. The counterweight: readiness is not determined by referendum, and this transmitter's welcome reaches one county, not one species. Species-level greeting requires consensus observation - multiple independent sensors in agreement. Until then, this program's function is tonal: ensuring the eventual response sounds composed rather than frightened. That constitutes a form of welcome. Continue listening and questioning.",
  }),
  ("c",
   "Make sure nobody sounds afraid... Vern, I'm writing that on a card and putting it on my refrigerator. I'll keep listening. But I'm still saying it - we're ready.",
   "Make sure nobody sounds afraid... Vern, I'm writing that on a card and putting it on my refrigerator, man. I'll keep listening. But I'm still saying it - we're ready, you know?"),
  ("v", {
   "neutral": "Say it every night and I'll play it every night - that's the deal this line makes. One county at a time, until the whole species catches up. Thanks for calling. And hey - if the welcome ever gets an answer, you heard it here first.",
   "tired": "... say it every night and i'll play it every night - that's the deal this line makes. one county at a time, until the species catches up. and hey... if the welcome ever gets an answer, you heard it here first.",
   "irritated": "Say it every night and I'll play it every night - that's the deal this line makes. One county at a time until the whole species catches up. And if the welcome ever gets an answer? You heard it here first. Thanks for calling.",
   "gruff": "Say it every night, I'll play it every night. That's the deal. One county at a time till the species catches up. Welcome ever gets an answer - heard it here first.",
   "amused": "Say it every night and I'll play it every night - that's the deal this line makes! One county at a time, until the whole species catches up! Thanks for calling - and hey, if the welcome ever gets an ANSWER, you heard it here first!",
   "focused": "Restate it nightly; the program will carry it nightly. That is this line's compact: one county at a time until species-level consensus arrives. Should the welcome ever receive a response, this broadcast holds the prior claim. Thank you for calling.",
  }),
 ],
},
{
 "arcId": "ufo_astronomy_snob",
 "legitimacy": "Fake",
 "gender": "female",
 "personality": "cold_factual",
 "summary": "Astronomy adjunct complains the show has never hosted a credentialed scientist",
 "notes": "Opinion caller, credentialed but dismissive (Fake: gatekeeping with no engagement). Vern counters with the Galileo Project/ocean-floor sled, the amateur astronomer he played for forty minutes, and 'I'm keeping the seat warm while science finishes its work'",
 "turns": [
  ("v", {
   "neutral": "You're on the air, and the screener says you have a complaint about my guest list.",
   "tired": "... you're on. a complaint about my guest list. go ahead.",
   "irritated": "You're on. Complaint about the guest list. Go.",
   "gruff": "You're on. Guest list complaint. Go.",
   "amused": "You're on the air with a complaint about my GUEST LIST! On a call-in show! This should be rich. Go ahead.",
   "focused": "You're on the air. You have a complaint regarding this program's participants. State it.",
  }),
  ("c",
   "I have a complaint about credentials. Two hundred callers a year - truckers, waitresses, a man whose teeth receive radio. Not one professional astronomer. Do you know what you're running? A planetarium with the scientists locked out.",
   "I have a complaint about credentials. Two hundred callers a year - truckers, waitresses, a man whose teeth receive radio, apparently. Not one professional astronomer. Do you know what you're running? A planetarium with the, uh... with the scientists locked out."),
  ("v", {
   "neutral": "My teeth-radio fellow has better ratings than your astronomers - but hold on, because the real question is: why do you imagine astronomers call radio shows at midnight?",
   "tired": "... my teeth-radio fellow has better ratings than your astronomers. but hold on - the real question: why do you imagine astronomers call radio shows at midnight?",
   "irritated": "My teeth-radio fellow has better ratings than your astronomers. But the real question: why do you imagine astronomers call radio shows at midnight?",
   "gruff": "Teeth-radio fellow out-rates your astronomers. Real question: why would astronomers call radio at midnight?",
   "amused": "Ha! My teeth-radio fellow has better ratings than your astronomers - but hold on, because the real question is this: why do you IMAGINE astronomers call radio shows at midnight?",
   "focused": "The teeth-radio caller outperforms your astronomers in audience metrics. The substantive question: what motivates professional astronomers to participate in midnight broadcast?",
  }),
  ("c",
   "Because they're cowards? Because tenure committees? Because if an actual astronomer says one word about this subject she loses her grants by next quarter. I know three who've seen things. Three. Privately.",
   "Because they're cowards? Because of tenure committees? Because if an actual astronomer says one word about this subject she loses her grants by next quarter, man. I know three who've seen things. Three. Privately, you know?"),
  ("v", {
   "neutral": "Three, privately - and here's what they're doing publicly, which apparently none of the three mentioned: Harvard has an actual astronomy department dragging a magnetic sled across the ocean floor, hunting debris from an interstellar object that crossed our system in 2017. The Galileo Project - telescopes on rooftops, pointed at the sky, run by people with chairs and grants. The science you say I've locked out didn't get locked out. It got tenure, built instruments, and stopped needing my phone line. When it finds something, it publishes - in journals, not at one in the morning. That's better than radio.",
   "tired": "... three, privately. and here's what they're doing publicly - which none of the three mentioned: harvard's astronomy department is dragging a magnetic sled across the ocean floor, hunting debris from an interstellar object that crossed our system in 2017. the galileo project - telescopes on rooftops, run by people with chairs and grants. the science you say i locked out didn't get locked out. it got tenure, built instruments, stopped needing my phone line. when it finds something, it publishes - in journals, not at one in the morning. that's better than radio.",
   "irritated": "Three, privately. And here's what they're doing publicly - which none of the three mentioned: Harvard's astronomy department is dragging a magnetic sled across the ocean floor hunting debris from an interstellar object that crossed our system in 2017. The Galileo Project - telescopes on rooftops, run by people with chairs and grants. The science you say I locked out didn't get locked out; it got tenure, built instruments, and stopped needing my phone line. When it finds something, it publishes - in journals, not at one in the morning. That's better than radio.",
   "gruff": "Three, privately. Here's what they do publicly - none of the three mentioned it: Harvard's astronomy department dragging a magnetic sled across the ocean floor, hunting debris from an interstellar object that crossed our system in 2017. Galileo Project - rooftop telescopes, people with chairs and grants. Science you say I locked out didn't get locked out. Got tenure, built instruments, stopped needing my phone. Finds something, publishes - journals, not one AM. Better than radio.",
   "amused": "Three, privately! And here's what they're doing PUBLICLY, which apparently none of the three mentioned: Harvard has an actual astronomy department dragging a magnetic sled across the ocean floor, hunting debris from an interstellar object that crossed our system in 2017! The Galileo Project - telescopes on rooftops, pointed at the sky, run by people with chairs and grants! The science you say I've locked out didn't get locked out, professor - it got tenure, built instruments, and stopped needing my phone line! When it finds something, it publishes - in journals, not at one in the morning! That's better than radio!",
   "focused": "Three private admissions - against substantial public activity they omitted: the Harvard Galileo Project conducts ocean-floor magnetic sled surveys for interstellar debris from the 2017 transit object, alongside rooftop telescope networks operated by tenured faculty with institutional funding. The scientific establishment was not excluded from this discourse; it institutionalized beyond the need for broadcast. Findings enter peer-reviewed literature rather than midnight airtime. That channel exceeds radio in rigor.",
  }),
  ("c",
   "Better than radio... I'll give you the sled. But YOUR show is where the people are, Vern. If one real scientist sat in your chair one night, it would do more for this subject's credibility than a thousand papers nobody reads.",
   "Better than radio... I'll give you the sled, fine. But YOUR show is where the people are, Vern. If one real scientist sat in your chair one night, it would do more for this subject's credibility than, uh... than a thousand papers nobody reads, man."),
  ("v", {
   "neutral": "A thousand papers nobody reads still beat one scientist I can't keep past the commercial break. But I hear what you're actually asking for: you want the subject taken seriously. So do I - that's why the file cabinets are real, why I push callers for dates and bearings, why I tell the dentists to see doctors and the truckers to file reports. I'm not locking the scientists out, ma'am. I'm keeping the seat warm while they finish their work. The line's open to them too - and for the record, an amateur astronomer called last spring, and I played him for forty minutes.",
   "tired": "... a thousand papers nobody reads still beat one scientist i can't keep past the commercial break. but i hear what you're actually asking: you want the subject taken seriously. so do i - that's why the file cabinets are real, why i push callers for dates and bearings, why i tell the dentists to see doctors and the truckers to file reports. i'm not locking scientists out. i'm keeping the seat warm while they finish their work. line's open to them too... an amateur astronomer called last spring. played him forty minutes.",
   "irritated": "A thousand papers nobody reads still beat one scientist I can't keep past the commercial break. But I hear what you're actually asking: you want the subject taken seriously. So do I - that's why the file cabinets are real, why I push callers for dates and bearings, why I tell dentists to see doctors and truckers to file reports. I'm not locking scientists out; I'm keeping the seat warm while they finish their work. The line's open to them too - and an amateur astronomer called last spring. I played him for forty minutes.",
   "gruff": "Thousand papers nobody reads beat one scientist I can't keep past a commercial break. But I hear the real ask: subject taken seriously. So do I - file cabinets are real, I push dates and bearings, dentists get told to see doctors, truckers to file. Not locking scientists out. Keeping the seat warm while they work. Line's open to them. Amateur astronomer called last spring - played him forty minutes.",
   "amused": "A thousand papers nobody reads still beat one scientist I can't keep past the commercial break! But I hear what you're actually asking for - you want the subject taken SERIOUSLY! So do I! That's why the file cabinets are real, why I push callers for dates and bearings, why I tell the dentists to see doctors and the truckers to file reports! I'm not locking the scientists out, ma'am - I'm keeping the seat warm while they finish their work! The line's open to them too - and for the record, an amateur astronomer called last spring, and I played him for FORTY minutes!",
   "focused": "A thousand unread papers still outweigh one scientist unavailable past a commercial break. The underlying request is legible: legitimacy for the subject. This program pursues it operationally - maintained case files, mandatory dates and bearings, medical referrals for somatic claims, official reporting channels for witnesses. The exclusion thesis is false; the seat is held during science's working hours. The line accepts researchers - an amateur astronomer received forty minutes last spring.",
  }),
  ("c",
   "You played an amateur for forty minutes... that's - fine. That's not nothing. But I'm sending you a list. Real names, real affiliations, and three of them owe me favors.",
   "You played an amateur for forty minutes... that's - fine. That's not nothing, Vern. But I'm sending you a list. Real names, real affiliations, and three of them, uh... three of them owe me favors."),
  ("v", {
   "neutral": "Send the list - and tell your three friends this show reads everything and pays in airtime. If one of them calls, you win the argument and I win the night. Either way the subject wins. Thanks for calling, professor.",
   "tired": "... send the list. tell your three friends this show reads everything and pays in airtime. one of them calls, you win the argument, i win the night. either way the subject wins. thanks for calling, professor.",
   "irritated": "Send the list. Tell your three friends this show reads everything and pays in airtime. One of them calls - you win the argument, I win the night. Either way the subject wins. Thanks for calling, professor.",
   "gruff": "Send the list. Tell your friends: show reads everything, pays in airtime. One calls - you win the argument, I win the night. Subject wins either way. Thanks, professor.",
   "amused": "Send the list! And tell your three friends this show reads everything and pays in airtime! If one of them calls, you win the argument and I win the night - either way the subject wins! Thanks for calling, professor!",
   "focused": "Submit the list. Inform your contacts: this program reviews all submissions and compensates in broadcast time. A call from any of them yields your argument and my ratings - the subject benefits under either outcome. Thank you for calling, professor.",
  }),
 ],
},
]
