# -*- coding: utf-8 -*-
# Batch 9 content: question wave complete + final opinion caller.

def V(neutral, tired=None, irritated=None, gruff=None, amused=None, focused=None):
    return {
        "neutral": neutral,
        "tired": tired or ("... " + neutral[:1].lower() + neutral[1:]),
        "irritated": irritated or neutral,
        "gruff": gruff or neutral,
        "amused": amused or neutral,
        "focused": focused or neutral,
    }


def C(text, voice=None):
    return ("c", text, voice or (text + " You know?"))


ARCS = [
{
 "arcId": "ufo_what_should_i_write",
 "legitimacy": "Questionable",
 "gender": "male",
 "personality": "cold_factual",
 "summary": "Methodical witness asks what to record before the memory edits itself",
 "notes": "Question arc. Vern gives a field-note protocol: time, direction, compass, weather, sound, smell, device behavior, witnesses, sketch first, interpretation last.",
 "turns": [
  ("v", V("You're on the air. You told the screener the sighting is over, but the note-taking is not. Go ahead.", "... you're on. sighting is over, note-taking isn't. go ahead.", gruff="You're on. Sighting's over. Notes aren't. Go.", amused="You're on the air with the best kind of panic: stationery panic. Go ahead.", focused="You're on the air. Your concern is documentation decay after an anomalous observation. Proceed.")),
  C("I saw a light do something it should not have done about forty minutes ago. I don't want to call it anything yet. I want to write it down before my brain improves the story. What should I write first?", "I saw a light do something it should not have done about forty minutes ago, man. I don't want to call it anything yet. I want to write it down before my brain improves the story. What should I write first, you know?"),
  ("v", V("Good. The first lie in any case file is usually the witness trying to make it sound better. Start ugly. Time, exact location, direction faced, where the object entered and left your view, and what you were doing when you first noticed it.", "... good. first lie in any case file is the witness making it sound better. start ugly. time, exact location, direction faced, where it entered and left your view, what you were doing when you noticed it.", gruff="Good. Start ugly: time, place, direction, entry, exit, what you were doing.", amused="Good! Ha - the first draft is where the truth hides before the brain combs its hair. Start ugly: time, place, direction, entry, exit, what you were doing.", focused="Correct instinct. Capture uninterpreted data first: time, precise location, viewing direction, entry and exit points, and your activity at first notice.")),
  C("I have time and road. I don't have compass. I can hear dogs still barking on the next block. Does that matter, or am I just collecting spooky details now?", "I have time and road. I don't have compass. I can hear dogs still barking on the next block, man. Does that matter, or am I just collecting spooky details now?"),
  ("v", V("It matters. Sound, smell, weather, power flickers, car radio, porch lights, phone battery, animals, and other witnesses. Don't decide which details are spooky. Write them all down and let tomorrow's boring explanation sort them.", "... it matters. sound, smell, weather, power flickers, car radio, porch lights, phone battery, animals, other witnesses. don't decide what's spooky. write it all down and let tomorrow's boring explanation sort it.", gruff="Matters. Sound, smell, weather, power, radio, lights, battery, animals, witnesses. Write all of it.", amused="It matters! Dogs have filed more honest sky reports than half the men who call me. Sound, smell, weather, power, radios, batteries, witnesses - all of it.", focused="Yes. Record environmental correlates: sound, odor, weather, electrical anomalies, radio behavior, device state, animals, and independent observers. Do not pre-filter.")),
  C("Should I sketch it? Because I draw like a crime scene witness in a comic strip. I don't want a bad drawing to make the real thing look fake."),
  ("v", V("Sketch it badly. Bad drawings are honest; polished drawings are auditions. Horizon line, rooftops, trees, moon if visible, object path, and your best guess at size. Label guesses as guesses. That's the trick.", "... sketch it badly. bad drawings are honest; polished drawings are auditions. horizon, rooftops, trees, moon, object path, best guess at size. label guesses as guesses.", gruff="Draw it badly. Horizon, roofs, trees, moon, path, size guess. Mark guesses as guesses.", amused="Sketch it badly! I trust a crooked line more than a perfect saucer. Horizon, rooftops, trees, moon, path, size - guesses labeled as guesses.", focused="Sketch immediately. Include horizon references, fixed landmarks, lunar position if present, object path, and estimated size. Explicitly mark estimates as estimates.")),
  C("No naming it. No improving it. Write the ugly version. I can do that. Anything I should not write?", "No naming it. No improving it. Write the ugly version. I can do that, man. Anything I should not write?"),
  ("v", V("Do not write the conclusion first. No 'ship,' no 'alien,' no 'drone' until the notes are done. Memory rewrites itself to match the headline, so deny it a headline. Date the page, keep the original, and if tomorrow the boring answer fails, this line wants the ugly version. Thanks for calling.", "... don't write the conclusion first. no ship, alien, drone until notes are done. memory rewrites itself to match the headline, so deny it a headline. date the page, keep the original, and if tomorrow's boring answer fails, this line wants the ugly version.", gruff="No conclusion first. No ship, alien, drone. Date it. Keep original. If boring fails tomorrow, call with the ugly version.", amused="Do not give memory a headline! No ship, no alien, no drone until the notes are done. Date the page, keep the original, and call me with the ugly version if boring fails.", focused="Withhold classification until after documentation. Terminology biases recall. Date the page, preserve the original, and submit the raw version if ordinary explanations fail. Thank you for calling.")),
 ],
},
{
 "arcId": "ufo_roadside_or_microsleep",
 "legitimacy": "Credible",
 "gender": "male",
 "personality": "nervous_hesitant",
 "summary": "Exhausted driver asks if roadside missing time was a sighting or microsleep",
 "notes": "Question arc. Vern treats both seriously: pull logs, fuel receipt, odometer, tachograph/ELD if any, sleep debt, and do not drive tonight.",
 "turns": [
  ("v", V("You're on the air. You sound tired enough that I want both hands on the wheel if you're calling from a car. Are you parked?", "... you're on. you sound tired enough that i want both hands off the wheel if you're calling from a car. are you parked?", gruff="You're on. First question: parked?", amused="You're on the air, and if this is a moving vehicle I am becoming your mother. Are you parked?", focused="You're on the air. Safety first: confirm you are parked before proceeding.")),
  C("Parked at a closed diner. I lost maybe twenty minutes on Route 6. There was a blue-white thing over the tree line, then I was three exits down with the radio off. I drive nights, Vern. What if I just nodded off?", "Parked at a closed diner, man. I lost maybe twenty minutes on Route 6. There was a blue-white thing over the tree line, then I was three exits down with the radio off. I drive nights, Vern. What if I just nodded off?"),
  ("v", V("Then we take nodding off seriously and we take the blue-white thing seriously. Those are not enemies; they're the two doors in front of you. How long since you slept, and do you have receipts or a log for the route?", "... then we take nodding off seriously and the blue-white thing seriously. not enemies. two doors. how long since sleep, and do you have receipts or a log?", gruff="Both serious. Sleep door, sky door. How long awake? Got receipts or logs?", amused="Ha - the rare caller asking me to talk him out of a UFO. Good. Sleep door and sky door. How long awake, and what paper trail do you have?", focused="We evaluate both hypotheses. Sleep interval, route documentation, receipts, and any vehicle logs are the first discriminators.")),
  C("Four hours of sleep yesterday. Coffee since midnight. Fuel receipt at 1:12, diner clock says 2:04 now. Odometer says I drove too far for the time I remember."),
  ("v", V("Four hours of sleep puts microsleep on the table. Odometer puts missing time on the table. Write both down without choosing. Photograph the receipt, the diner clock, odometer, fuel gauge, and the radio setting. If your truck has any electronic log, pull it before anything rolls over.", "... four hours puts microsleep on the table. odometer puts missing time on the table. write both without choosing. photo receipt, clock, odometer, fuel gauge, radio. pull any electronic log before it rolls over.", gruff="Sleep is on the table. Missing time is on the table. Photo receipt, clock, odometer, fuel gauge, radio. Pull logs.", amused="That is exactly the kind of boring paperwork that saves a weird night from becoming campfire smoke. Photograph everything and pull the truck data.", focused="Sleep debt supports microsleep; odometer discrepancy supports temporal anomaly. Preserve contemporaneous records: receipt, clock, odometer, fuel gauge, radio state, and electronic logs.")),
  C("I keep wanting you to tell me which one it was. Because if it was sleep, I'm dangerous. If it wasn't sleep, I don't know what I am."),
  ("v", V("Tonight, you're a man who should not drive. That's the only answer I will give live on air. Call dispatch, call a motel, call someone mad enough to come get you. The investigation can wait until daylight; the guardrail will not.", "... tonight, you're a man who should not drive. that's the only answer i give live on air. call dispatch, motel, somebody mad enough to get you. investigation waits for daylight. guardrail doesn't.", gruff="Tonight you're not driving. Call dispatch, motel, friend. Weird can wait. Guardrails don't.", amused="I can argue with aliens later; I will not argue with a ditch tonight. You are done driving until daylight.", focused="Immediate operational conclusion: cease driving. Arrange dispatch relief, lodging, or pickup. Case analysis is secondary to collision prevention.")),
  C("I hate that answer. I also needed it. I'm calling dispatch after this. If the logs show something strange, can I call back?"),
  ("v", V("You call back with the logs, rested, parked, and angry at me if you want. I'll take angry over asleep every time. Keep the receipt, keep the odometer photo, sleep before you solve the sky. Thanks for calling.", "... call back with the logs, rested, parked, angry at me if you want. i'll take angry over asleep. keep the receipt, odometer photo, sleep before solving the sky.", gruff="Call back rested and parked. Keep the paper. Sleep before the sky.", amused="Call back mad and well-rested. That's my favorite kind of alive caller. Keep the paper trail and sleep before you solve the universe.", focused="Return with documentation only after rest. Preserve records and prioritize sleep before analysis. Thank you for calling.")),
 ],
},
{
 "arcId": "ufo_still_believe_eyes",
 "legitimacy": "Credible",
 "gender": "female",
 "personality": "official",
 "summary": "Eighty-one-year-old witness asks whether age means she should stop trusting her eyes",
 "notes": "Question arc. Vern says witnesses do not expire; separate eye health from credibility, write it down, and let younger family help verify landmarks instead of dismissing her.",
 "turns": [
  ("v", V("You're on the air. You told the screener your family says this is about age. You aren't sure they're wrong. Go ahead.", "... you're on. family says this is about age. you aren't sure they're wrong. go ahead.", gruff="You're on. Family says age. You aren't sure. Go.", amused="You're on the air, and apparently the family has diagnosed the entire sky. Go ahead.", focused="You're on the air. The contested factor is age and visual reliability. Proceed.")),
  C("I'm eighty-one. Last night I saw three orange lights over the water tower. My daughter said, gently, that eyes play tricks. She wasn't cruel. That's what made it worse. At what age do I stop being a witness and become a symptom?", "I'm eighty-one, man. Last night I saw three orange lights over the water tower. My daughter said, gently, that eyes play tricks. She wasn't cruel. That's what made it worse. At what age do I stop being a witness and become a symptom?"),
  ("v", V("You do not age out of being a witness. You age into knowing the difference between what you saw and what you think it means. That is a better witness, not a worse one. Have you had your eyes checked recently?", "... you do not age out of being a witness. you age into knowing the difference between what you saw and what you think it means. better witness, not worse. eyes checked recently?", gruff="Witnesses don't expire. Eyes get checked. Both true. Recent eye exam?", amused="If age disqualified witnesses, half of Blue Book would be written by empty chairs. You still count. Have the eyes been checked?", focused="Witness status does not expire. Visual health should be evaluated separately from testimonial value. Recent eye examination?")),
  C("Last spring. Cataract surgery two years ago, good results. I know planes. I know the tower lights. These were above it, moving together, then gone. But my daughter looked so sad, Vern."),
  ("v", V("Then give your daughter a job that isn't dismissing you. Ask her to drive you to the spot, photograph the tower from where you stood, note the weather, and check flight traffic. Families do better with assignments than with fear.", "... give your daughter a job that isn't dismissing you. drive to the spot, photo the tower, note weather, check flight traffic. families do better with assignments than fear.", gruff="Give her a job: spot, photo, weather, traffic. Better than dismissal.", amused="Turn the sadness into clerical work. Families are less dangerous when holding a clipboard.", focused="Convert family concern into verification tasks: site photo, weather record, flight traffic review, and landmark confirmation.")),
  C("I like that. A job, not a verdict. But if it turns out to be nothing, I don't want her thinking she was right about me."),
  ("v", V("If it turns out to be nothing, she was right about the lights, not about you. Those are different cases. Good witnesses are allowed to be mistaken; bad witnesses refuse to find out.", "... if it's nothing, she was right about the lights, not about you. different cases. good witnesses can be mistaken; bad witnesses refuse to find out.", gruff="Wrong about lights isn't wrong about you. Good witnesses can be mistaken.", amused="Let her win the plane and lose the insult. That's family diplomacy.", focused="An ordinary explanation would resolve the event, not diminish the observer. Credible witnesses can be mistaken; credibility includes testing.")),
  C("Right about the lights, not about me. I can say that to her. I think I needed permission to still be useful."),
  ("v", V("You are useful. Write the account tonight in your own hand: time, tower, direction, color, motion. Then let your daughter help check the world around it. The eye is the first instrument. It gets calibrated; it does not get thrown away. Thanks for calling.", "... you're useful. write it tonight in your hand: time, tower, direction, color, motion. let your daughter check the world around it. the eye is the first instrument. calibrated, not thrown away.", gruff="Write it tonight. Let her verify. First instrument gets calibrated, not thrown away.", amused="Useful? Ma'am, you just improved half my callers by asking for verification. Write it, check it, keep your eyes in the case.", focused="Document tonight, then verify collaboratively. The eye is the first instrument: calibrate it, do not discard it. Thank you for calling.")),
 ],
},
{
 "arcId": "ufo_have_you_seen_one",
 "legitimacy": "Questionable",
 "gender": "male",
 "personality": "enthusiastic_convert",
 "summary": "Caller asks whether Vern has personally seen a UFO",
 "notes": "Question arc. Vern uses the childhood Venus/dead-air canon: he saw something, later learned the sky, and kept both humility and hunger for the unsolved.",
 "turns": [
  ("v", V("You're on the air. The screener wrote one sentence: ask Vern the thing. I dislike how much I know what that means. Go ahead.", "... you're on. screener wrote: ask vern the thing. i dislike how much i know what that means. go ahead.", gruff="You're on. Ask the thing.", amused="You're on the air with the question every host eventually earns. Go ahead, hit me.", focused="You're on the air. You have a direct question for me. Proceed.")),
  C("Have you seen one? Not read about one, not interviewed somebody, not 'I know a pilot.' You, Vern. Have you personally seen a UFO?", "Have you seen one, man? Not read about one, not interviewed somebody, not 'I know a pilot.' You, Vern. Have you personally seen a UFO?"),
  ("v", V("I saw something when I was ten that I called a UFO for about six glorious hours. A white star followed our car over a county road, stopped when we stopped, and terrified me into religion and astronomy in the same evening.", "... i saw something at ten i called a ufo for six glorious hours. white star followed our car, stopped when we stopped, terrified me into religion and astronomy in one evening.", gruff="Age ten. White star. Followed the car. Six hours of UFO before astronomy ruined it.", amused="I had six perfect hours as an abductee candidate before Venus kicked the door in.", focused="At age ten I observed a bright object apparently pacing a car. Subjectively anomalous; later likely Venus through moving reference frames.")),
  C("Venus? You're going to tell me it was Venus. Vern, come on. You of all people?"),
  ("v", V("Venus is not a joke answer. Venus has ruined more UFO reports than hoaxers have. Bright, low, patient, and perfectly willing to make a moving car feel chosen. Learning that didn't kill my interest. It taught me the sky gets a vote.", "... venus isn't a joke answer. ruined more ufo reports than hoaxers. bright, low, patient, makes a moving car feel chosen. didn't kill my interest. taught me the sky gets a vote.", gruff="Venus isn't a punchline. It fools honest people. Fooled me. Sky gets a vote.", amused="Venus is the trickster god of county roads, and I will not slander her craftsmanship.", focused="Venus is a significant false-positive source: bright, low, persistent, and reference-frame deceptive. The lesson is methodological, not dismissive.")),
  C("But was there ever one you couldn't explain? One that stayed in the file after the boring answers took their shot?"),
  ("v", V("Yes. Other people's. A radar operator who hated attention. A ferry captain who knew every light on the water. A mother who kept a child's drawing for thirty years. I have cases I cannot close. That is different from pretending every light is mine.", "... yes. other people's. radar operator, ferry captain, mother with a child's drawing. cases i can't close. different from pretending every light is mine.", gruff="Yes. Other people's. Radar, ferry, mother's drawing. Unclosed cases. Not every light is mine.", amused="I collect other people's unclosed drawers. Mine had Venus in it. Some of theirs do not.", focused="Yes: cases from disciplined observers remain unresolved. My personal Venus event is not among them. Distinguishing those categories is essential.")),
  C("So you believe because of witnesses, not because you had your own miracle."),
  ("v", V("I keep the line open because witnesses deserve a place where the first answer is not laughter and the last answer is not fantasy. My miracle was being wrong and still wanting the truth. That is enough fuel for a late-night show. Thanks for calling.", "... i keep the line open because witnesses deserve a place where first answer isn't laughter and last answer isn't fantasy. my miracle was being wrong and still wanting truth. enough fuel for a late-night show.", gruff="Line stays open for witnesses. First answer not laughter. Last answer not fantasy. My miracle was being wrong and staying curious.", amused="My saucer became a planet and somehow I got a radio career out of it. There are worse origin stories.", focused="This program exists for disciplined witness testimony: neither ridicule nor fantasy as default. My formative event was misidentification followed by continued inquiry. Thank you for calling.")),
 ],
},
{
 "arcId": "ufo_alien_ballot",
 "legitimacy": "Fake",
 "gender": "female",
 "personality": "charismatic_storyteller",
 "summary": "Local candidate running on disclosure wants Vern's endorsement",
 "notes": "Opinion arc. Vern refuses endorsement, explains disclosure politics is old but the show is not a precinct, and redirects her to public records and boring civic work.",
 "turns": [
  ("v", V("You're on the air. You are running for local office, and I can already hear my producer aging. Go ahead.", "... you're on. running for local office, and i can hear my producer aging. go ahead.", gruff="You're on. Candidate. Go.", amused="You're on the air, candidate, and every lawyer listening just sat up. Go ahead.", focused="You're on the air. You are a local candidate with a disclosure platform. Proceed carefully.")),
  C("Vern, I'm running for county commissioner on a full disclosure platform: open the airport records, publish police calls about lights, no more laughing at witnesses. I want your endorsement tonight.", "Vern, I'm running for county commissioner on a full disclosure platform: open the airport records, publish police calls about lights, no more laughing at witnesses. I want your endorsement tonight, man."),
  ("v", V("You are getting air, not endorsement. This line is not a precinct, a pulpit, or a campaign office. But I will ask the same question I ask every candidate with a sky full of slogans: what records can a county commissioner actually release?", "... you're getting air, not endorsement. this line is not a precinct. but same question for every sky-slogan candidate: what records can a county commissioner actually release?", gruff="Air, not endorsement. What records can your office actually release?", amused="You may have thirty seconds of radio and zero percent of my ballot. What records can the office release?", focused="No endorsement. Clarify jurisdiction: which records fall under county authority?")),
  C("Sheriff calls, airport incident notes, emergency dispatch logs, maybe school reports if parents consent. The point is sunlight."),
  ("v", V("Sunlight is good. Campaign fog is not. Sheriff logs and dispatch records may be public already; airport notes may be federal-adjacent; school reports involve minors, so slow down before you make a billboard out of a frightened child.", "... sunlight good. campaign fog isn't. sheriff and dispatch may already be public; airport notes may be federal-adjacent; school reports involve minors, so slow down.", gruff="Sunlight good. Fog bad. Public records already exist. Kids are not campaign props.", amused="Nothing says responsible government like not turning a fifth grader's weird recess into a yard sign.", focused="Public-records law, federal aviation jurisdiction, and minor privacy constraints must be separated before promising disclosure.")),
  C("So you don't want disclosure? That's what my opponent says: everybody asks for truth until someone runs on it."),
  ("v", V("I want disclosure that survives the first clerk with a stamp. File public-records requests, publish what you lawfully get, redact minors, and explain boring limits before promising cosmic ones. That's civic work, not a bumper sticker.", "... i want disclosure that survives the first clerk with a stamp. file records requests, publish lawful records, redact minors, explain boring limits before cosmic promises. civic work, not bumper sticker.", gruff="Do records requests. Publish lawful records. Redact kids. Boring first, cosmic later.", amused="Give me a candidate who can love a filing cabinet before she marries a mothership.", focused="Viable disclosure begins with lawful requests, publication of obtained records, privacy redaction, and transparent jurisdictional limits.")),
  C("I can do boring. I was hoping boring would sound more heroic on radio, but I can do it."),
  ("v", V("Boring is heroic when it produces documents. No endorsement, no campaign slogan from me. But if you win and publish a clean county incident archive, this line will read the records on air and give the work its due. That's the best deal you're getting. Thanks for calling.", "... boring is heroic when it produces documents. no endorsement, no slogan. win and publish a clean county incident archive, and this line reads the records on air. best deal you're getting.", gruff="No endorsement. Publish clean records. I'll read the work. Best deal.", amused="Win me a filing cabinet and I'll throw it a parade. Until then, no endorsement.", focused="No endorsement. If elected and if a lawful, redacted incident archive is published, this program will report on the records. Thank you for calling.")),
 ],
},
]
