# -*- coding: utf-8 -*-
# Batch 3 content (part 2): opinion wave 3.
ARCS = [
{
 "arcId": "ufo_they_run_dmv",
 "legitimacy": "Fake",
 "gender": "male",
 "personality": "charismatic_storyteller",
 "summary": "Caller's theory: they've been here for decades and they run the DMV",
 "notes": "Comedy opinion arc - no evidence, pure vibes (Fake). Vern plays along, shares the infiltration-theory history (body-snatcher panics, '50s neighbors-replaced fear), then lands the real point: the theory says more about us than them",
 "turns": [
  ("v", {
   "neutral": "You're on the air. You told the screener you know where they are right now, and you don't mean the sky.",
   "tired": "... you're on. you know where they are right now. not the sky. where?",
   "irritated": "You're on. You know where they are - not the sky. Where?",
   "gruff": "You're on. Where are they?",
   "amused": "You're on the air and you know where they are RIGHT NOW - and it's not the sky! Alright, I'm all ears.",
   "focused": "You're on the air. You claim to know the current location of the phenomena. State it.",
  }),
  ("c",
   "They're at the DMV, Vern. Third window. Have been for decades. Think about it! The waiting, the forms that make no sense, the numbers that never get called, the feeling that something is observing you through glass and finding you inadequate - that's not government. That's a study! We've been the exhibit this whole time and the admission is free!",
   "They're at the DMV, Vern. Third window. Have been for decades, man. Think about it! The waiting! The forms that make no sense! The numbers that never get called! The feeling that something is observing you through glass and finding you inadequate - that's not government. That's a study! We've been the exhibit this whole time and the, uh... the admission is free!"),
  ("v", {
   "neutral": "I've been doing this show long enough to know a theory when the teller is having fun with it - and you are. So here's my counter, offered in the same spirit: every generation picks the institution it trusts least and moves them in. The fifties had neighbors replaced by something wearing their faces. The seventies had them in the phone company. The nineties, the malls. The theory is never about them. It's a portrait of us, at whichever counter we feel smallest.",
   "tired": "... i've done this long enough to know a theory when the teller's having fun - and you are. so the counter, same spirit: every generation picks the institution it trusts least and moves them in. fifties - neighbors replaced by something wearing their faces. seventies - the phone company. nineties - the malls. the theory's never about them... it's a portrait of us, at whichever counter we feel smallest.",
   "irritated": "I've done this long enough to know a theory when the teller's having fun - and you are. Counter, same spirit: every generation picks the institution it trusts least and moves them in. The fifties - neighbors replaced by something wearing their faces. Seventies - the phone company. Nineties - the malls. The theory's never about them. It's a portrait of us, at whichever counter we feel smallest.",
   "gruff": "Done this long enough to know when the teller's having fun. Counter, same spirit: every generation moves them into whatever institution it trusts least. Fifties - replaced neighbors. Seventies - phone company. Nineties - malls. Never about them. Portrait of us, at whichever counter we feel smallest.",
   "amused": "Ha! I've been doing this show long enough to know a theory when the teller is having FUN with it - and you are having fun! So here's my counter, offered in the same spirit: every generation picks the institution it trusts least and moves them in! The fifties - neighbors replaced by something wearing their faces! The seventies - the phone company! The nineties - the malls! The theory is never about them, my friend. It's a portrait of us, at whichever counter we feel smallest!",
   "focused": "I recognize an entertaining hypothesis when the proponent enjoys it - and you do. The counter-observation: infiltration theories consistently target whichever institution holds the least public trust in a given era. 1950s - replaced neighbors. 1970s - telecommunications. 1990s - retail complexes. The pattern documents institutional distrust, not visitor behavior. The theory is a self-portrait rendered at the counter where the subject feels smallest.",
  }),
  ("c",
   "A self-portrait at the counter... alright, alright, that's good, I'm not even mad. But admit one thing, Vern - just one: the third window has no soul and everyone who's ever stood in that line knows it.",
   "A self-portrait at the counter... alright, alright, that's good, I'm not even mad, man. But admit one thing, Vern - just one: the third window has no soul, and everyone who's ever stood in that line knows it, you know?"),
  ("v", {
   "neutral": "The third window has no soul - stipulated, entered into the record, no argument from this chair. And here's the thing your joke theory gets right by accident: real or not, that line teaches people something true about being watched, being numbered, being processed by something that doesn't explain itself. Maybe that's why every decade files the same report at a different address. We keep recognizing the feeling. Next caller - and whoever's at the third window, keep up the good work.",
   "tired": "... the third window has no soul - stipulated, entered into the record. and here's what your joke gets right by accident: real or not, that line teaches something true about being watched, numbered, processed by something that doesn't explain itself. maybe that's why every decade files the same report at a different address. we keep recognizing the feeling. next caller.",
   "irritated": "The third window has no soul - stipulated, entered into the record, no argument from this chair. And your joke theory gets one thing right by accident: real or not, that line teaches people something true about being watched, numbered, processed by something that won't explain itself. Maybe that's why every decade files the same report at a different address. We keep recognizing the feeling. Next caller.",
   "gruff": "Third window has no soul - stipulated, in the record. And your joke's right about one thing by accident: that line teaches people what being watched, numbered, processed by something that won't explain itself feels like. Maybe that's why every decade files the same report at a new address. We keep recognizing the feeling. Next caller.",
   "amused": "The third window has NO SOUL - stipulated! Entered into the record! No argument from this chair! And here's what your joke theory gets right by accident: real or not, that line teaches people something true about being watched, being numbered, being processed by something that doesn't explain itself! Maybe that's why every decade files the same report at a different address - we keep recognizing the feeling! Next caller - and whoever's working the third window, keep up the good work!",
   "focused": "Proposition stipulated: the third window has no soul; entered into the record without contest. Your hypothesis accidentally identifies the mechanism: the queue experience - observed, numbered, processed by an unexplained authority - rehearses the phenomenology of encounter reports. Each decade refiles the same complaint at a new institutional address because the feeling is recognizable. Next caller.",
  }),
 ],
},
{
 "arcId": "ufo_book_deal",
 "legitimacy": "Fake",
 "gender": "male",
 "personality": "official",
 "summary": "Self-published author demands airtime to plug his unified theory book",
 "notes": "Opinion/self-promo caller (Fake: no experience, wants the platform). Vern refuses plugs on principle, shares the show's 40-year pitch history and what separates a manuscript from an argument, then offers the real door: send it, the show reads everything, ideas get air - marketing doesn't",
 "turns": [
  ("v", {
   "neutral": "You're on the air. The screener wrote down 'author' and then, I see, 'important.' Go ahead.",
   "tired": "... you're on. the screener wrote 'author' and then, i see, 'important.' go ahead.",
   "irritated": "You're on. The screener wrote 'author,' then 'important.' Go.",
   "gruff": "You're on. Author. Important. Go.",
   "amused": "You're on the air! The screener wrote down 'author' and then - I'm reading this correctly - 'important'! Alright, important author, the floor is yours.",
   "focused": "You're on the air. The screening note reads 'author,' annotated 'important.' Proceed.",
  }),
  ("c",
   "I'll be brief and I'll be generous. I have a book - four hundred pages, six years - that unifies the sightings, the abductions, and the crop circles under one physical theory. It's self-published because the gatekeepers wouldn't touch it, which tells you everything. What I need from you is ten minutes, three times a week, to explain it to an audience that's already interested. I'll even do it for free.",
   "I'll be brief and I'll be generous. I have a book - four hundred pages, six years - that unifies the sightings, the abductions, and the crop circles under one physical theory. It's self-published because the gatekeepers wouldn't touch it, which tells you everything, frankly. What I need from you is ten minutes, three times a week, to explain it to an audience that's already interested. I'll even, uh... I'll even do it for free."),
  ("v", {
   "neutral": "Free is still a price, sir - it costs me my listeners' trust, and that's the only currency this show has. So let me tell you what forty years of this line has taught me about books. I've been pitched thousands. The ones that mattered didn't ask for airtime - they answered questions. They brought a case, a file, a date, a witness. Six years is real work and I respect the labor; but a theory that unifies everything explains nothing I can check, and this show runs on things I can check.",
   "tired": "... free is still a price, sir - it costs me my listeners' trust, and that's the only currency this show has. forty years of this line: pitched thousands of books. the ones that mattered didn't ask for airtime - they answered questions. brought a case, a file, a date, a witness. six years is real work, i respect the labor. but a theory that unifies everything explains nothing i can check... and this show runs on things i can check.",
   "irritated": "Free is still a price, sir - it costs me my listeners' trust, the only currency this show has. Forty years on this line, I've been pitched thousands of books. The ones that mattered didn't ask for airtime - they answered questions. Brought a case, a file, a date, a witness. Six years is real work and I respect the labor. But a theory that unifies everything explains nothing I can check - and this show runs on things I can check.",
   "gruff": "Free is still a price - costs my listeners' trust. Only currency here. Forty years, pitched thousands of books. The ones that mattered didn't ask for airtime. Answered questions. Brought a case, a file, a date, a witness. Six years is real work. Respect the labor. But a theory unifying everything explains nothing I can check. This show runs on checkable.",
   "amused": "Ha - free is STILL a price, sir! It costs me my listeners' trust, and that's the only currency this show has! So let me tell you what forty years of this line taught me about books: I've been pitched THOUSANDS! The ones that mattered didn't ask for airtime - they answered questions! Brought a case, a file, a date, a witness! Six years is real work and I respect the labor - but a theory that unifies everything explains nothing I can check, and this show runs on things I can CHECK!",
   "focused": "'Free' carries a cost: listener trust, this program's only currency. Forty years of submissions yield one discriminator - consequential books answered questions rather than requesting platforms. They presented cases, files, dates, witnesses. Six years of labor commands respect; however, a theory unifying all phenomena is unfalsifiable by construction, and this program operates on verifiable claims.",
  }),
  ("c",
   "Unfalsifiable is a word people use when they haven't read chapter four. Chapter four has predictions, Vern - dated ones. And for the record, the gatekeepers said the same thing to every author who was early. I'm not asking for belief. I'm asking for ten minutes.",
   "Unfalsifiable is a word people use when they haven't read chapter four. Chapter four has predictions, Vern - dated ones. And for the record, the gatekeepers said the same thing to every author who was early, you know? I'm not asking for belief. I'm asking for ten minutes, man."),
  ("v", {
   "neutral": "Dated predictions in chapter four - now THAT is a sentence that changes this conversation, and you buried it under six years and a grievance. Here's the deal, and it's the only deal this show makes: send me the manuscript. Not a pitch - the manuscript. We read everything; that's not a slogan, it's a schedule, and it's why the file cabinets behind me are full. If chapter four predicts and the predictions land, you won't need my ten minutes - the story will take them, and I'll be first in line to read it on air. Ideas get air here. Marketing doesn't. Mail the book.",
   "tired": "... dated predictions in chapter four - now that changes the conversation, and you buried it under six years and a grievance. the deal's the only one this show makes: send the manuscript. not a pitch. we read everything - not a slogan, a schedule, it's why the cabinets behind me are full. chapter four predicts and the predictions land, you won't need my ten minutes - the story takes them. ideas get air here. marketing doesn't. mail the book.",
   "irritated": "Dated predictions in chapter four - THAT changes the conversation, and you buried it under six years and a grievance. The deal is the only one this show makes: send the manuscript, not a pitch. We read everything - not a slogan, a schedule; it's why the cabinets behind me are full. If chapter four predicts and the predictions land, you won't need my ten minutes - the story will take them. Ideas get air here. Marketing doesn't. Mail the book.",
   "gruff": "Dated predictions in chapter four - that changes it. You buried the lead under six years and a grievance. The deal: send the manuscript. Not a pitch. We read everything - schedule, not slogan, why the cabinets are full. Predictions land, you won't need my ten minutes - the story takes them. Ideas get air. Marketing doesn't. Mail the book.",
   "amused": "Dated predictions in chapter four?! NOW that is a sentence that changes this conversation - and you buried it under six years and a grievance! Here's the deal, and it's the only deal this show makes: send me the MANUSCRIPT! Not a pitch - the manuscript! We read everything; that's not a slogan, it's a schedule - it's why the file cabinets behind me are full! If chapter four predicts and the predictions LAND, you won't need my ten minutes - the story will take them, and I'll be first in line to read it on air! Ideas get air here! Marketing doesn't! MAIL THE BOOK!",
   "focused": "Dated predictions materially change the classification - and you positioned them fourth, behind grievance. Terms: submit the manuscript, not promotional material. This program reads all submissions on a standing schedule; the archive behind me is the evidence. If chapter four's predictions verify, airtime becomes unnecessary - the result will command it. Ideas receive broadcast; marketing does not. Submit the manuscript.",
  }),
  ("c",
   "Mail the book... alright. Alright! I'll mail the book. And when chapter four lands - because it will land - I want it in writing that you said 'first in line.'",
   "Mail the book... alright. Alright! I'll mail the book, man. And when chapter four lands - because it will land - I want it in writing that you said, uh... 'first in line.'"),
  ("v", {
   "neutral": "It's in writing - it's on tape, which is better, and a hundred thousand people just heard it. Mail the book, author. If the predictions land, you'll have your ten minutes and my apology, in that order. Thanks for calling.",
   "tired": "... it's on tape, which beats writing, and a hundred thousand people heard it. mail the book. predictions land, you get ten minutes and my apology, in that order.",
   "irritated": "It's on tape - which beats writing - and a hundred thousand people just heard it. Mail the book, author. Predictions land, you get your ten minutes and my apology, in that order. Thanks for calling.",
   "gruff": "On tape. Beats writing. Hundred thousand heard it. Mail the book. Predictions land - ten minutes and my apology, that order.",
   "amused": "It's in writing - it's on TAPE, which is better, and a hundred thousand people just heard it! Mail the book, author! If the predictions land, you'll have your ten minutes AND my apology - in that order! Thanks for calling!",
   "focused": "The commitment is recorded on broadcast media - superior to writing - with an audience of approximately one hundred thousand. Submit the manuscript. Verification earns airtime and my retraction, in that sequence. Thank you for calling.",
  }),
 ],
},
]
