# -*- coding: utf-8 -*-
# Batch 2 content (part 2): opinion wave 2.
ARCS = [
{
 "arcId": "ufo_town_coverup",
 "legitimacy": "Questionable",
 "gender": "female",
 "personality": "gruff_experienced",
 "summary": "Diner owner says her whole town watches the ridge lights and nobody reports them - property values",
 "notes": "Opinion caller grounded in real small-town economics. Vern validates the pattern (Socorro, Belgium), then pushes: hearsay until two signatures. His gift is the booth-notebook workaround - initials, not names",
 "turns": [
  ("v", {
   "neutral": "You're on the air. You said your whole town sees them and not one soul reports it.",
   "tired": "... you're on. the whole town sees them. nobody reports it. go ahead.",
   "irritated": "You're on. The whole town sees them, nobody reports. Explain that.",
   "gruff": "You're on. Whole town sees them. Nobody talks. Go.",
   "amused": "You're on the air with a town full of witnesses and not one report! Alright - how does that work?",
   "focused": "You're on the air. You describe community-wide observation with zero reporting. Go on.",
  }),
  ("c",
   "I've run the diner on Route 9 for twenty-two years. Every booth in that place has heard it: lights over the ridge, two, three nights a week since spring. And not one soul will put it in writing - because the minute it's in the paper, the town's name means something different. Who buys a house in the UFO town? My sister-in-law listed hers in June. Nobody talks. Everybody watches.",
   "I've run the diner on Route 9 for twenty-two years. Every booth in that place has heard it: lights over the ridge, two, three nights a week since spring. And not one soul will put it in writing - because the minute it's in the paper, the town's name means something different. Who buys a house in the, uh... in the UFO town? My sister-in-law listed hers in June. Nobody talks. Everybody watches, you know?"),
  ("v", {
   "neutral": "So the cover-up isn't the government. It's the multiple listing service.",
   "tired": "... so the cover-up isn't the government. it's the multiple listing service.",
   "irritated": "So the cover-up isn't the government - it's the multiple listing service.",
   "gruff": "So the cover-up isn't the government. It's the MLS.",
   "amused": "Ha! So the cover-up isn't the government - it's the multiple listing service!",
   "focused": "So the suppression mechanism is economic, not institutional - real estate.",
  }),
  ("c",
   "Laugh it up, but it's true. You want names? Fine - the Henderson place sold in nine days once they stopped asking questions at the diner. You want witnesses? Half my regulars. You want them on the phone? That's the part nobody wants. What am I supposed to do, Vern - be the one who says it?",
   "Laugh it up, but it's true. You want names? Fine - the Henderson place sold in nine days once they stopped asking questions at the diner. You want witnesses? Half my regulars. You want them on the phone? That's, uh... that's the part nobody wants. What am I supposed to do, Vern - be the one who says it?"),
  ("v", {
   "neutral": "I'll tell you what's in my files, because your town isn't the only one in them. There are towns where sightings doubled the same year the paper stopped printing them - the Socorro flap in '64 had a sheriff begging reporters off. Belgium, '89: gendarmes tracked it, the whole country knew, and town councils still kept quiet so buyers wouldn't spook. The economics are real. But here's my honest push: half my regulars is hearsay until two of them sign their own names. Silence isn't proof of lights. It's proof of a housing market.",
   "tired": "... your town isn't the only one in my files. towns where sightings doubled the year the paper stopped printing - socorro, '64, a sheriff begging reporters off. belgium, '89 - gendarmes tracked it, councils kept quiet so buyers wouldn't spook. the economics are real. but half my regulars is hearsay until two of them sign names. silence isn't proof of lights... it's proof of a housing market.",
   "irritated": "Your town isn't the only one in my files. Towns where sightings doubled the year the paper stopped printing - Socorro in '64, a sheriff begging reporters off. Belgium in '89 - gendarmes tracked it, councils kept quiet. The economics are real. But 'half my regulars' is hearsay until two of them sign names. Silence isn't proof of lights - it's proof of a housing market.",
   "gruff": "Your town isn't the only one in my files. Socorro, '64 - sheriff begged reporters off. Belgium, '89 - gendarmes tracked it, councils kept quiet. Economics are real. But 'half my regulars' is hearsay till two sign names. Silence isn't proof of lights. It's proof of a housing market.",
   "amused": "Let me tell you what's in my files, because your town is far from the only one in them! Towns where sightings DOUBLED the same year the paper stopped printing - Socorro in '64, a sheriff begging reporters off! Belgium in '89 - gendarmes tracking triangles while town councils kept quiet so buyers wouldn't spook! The economics are real, they're practically a genre! But here's my push, and it's an honest one: half my regulars is hearsay until two of them sign their own names. Silence isn't proof of lights, my friend - it's proof of a housing market!",
   "focused": "The pattern is documented: Socorro 1964, where the sheriff actively discouraged press coverage during a landing report; Belgium 1989-90, where municipal authorities suppressed discussion during gendarmerie radar tracking. Economic suppression of reporting is a recurring variable. However, 'half my regulars' remains hearsay absent two signed attestations. Silence evidences market pressure, not aerial phenomena.",
  }),
  ("c",
   "Two of them... you think I can get two people in that diner to sign anything? I've known these folks twenty years. They won't even say it out loud after dark.",
   "Two of them... you think I can get two people in that diner to sign anything? I've known these folks twenty years. They won't even, um... they won't even say it out loud after dark."),
  ("v", {
   "neutral": "Then don't ask for names - ask for a log. A booth notebook. Anybody who saw something writes initials, date, time, direction. Initials don't go on the listing, they don't scare buyers, and they don't make the paper - until there are forty entries and a reporter wonders why the diner keeps a book about the sky. That's how a town talks without talking. Start the notebook tomorrow.",
   "tired": "... then don't ask for names. ask for a log. a booth notebook. anybody who saw something writes initials, date, time, direction. initials don't go on a listing, don't scare buyers, don't make the paper - until there's forty entries and a reporter wonders why the diner keeps a book about the sky. that's how a town talks without talking. start it tomorrow.",
   "irritated": "Then don't ask for names - ask for a log. A booth notebook. Initials, date, time, direction. Initials don't go on a listing and don't scare buyers - until there are forty entries and a reporter wonders why the diner keeps a book about the sky. That's how a town talks without talking. Start it tomorrow.",
   "gruff": "Then don't ask for names. Ask for a log. Booth notebook. Initials, date, time, direction. Doesn't hit a listing, doesn't scare buyers - till forty entries and a reporter asks why the diner keeps a book about the sky. Town talks without talking. Start tomorrow.",
   "amused": "Then don't ask for names - ask for a LOG! A booth notebook! Anybody who saw something writes initials, date, time, direction! Initials don't go on a listing, they don't scare buyers, and they don't make the paper - until there are forty entries and some reporter wonders why the diner keeps a book about the sky! Ha - that's how a town talks without talking! Start the notebook tomorrow!",
   "focused": "Substitute attestation with documentation: a booth log capturing initials, date, time, and bearing. Initials carry no market consequence and no publication risk - until entry volume itself becomes newsworthy. Distributed anonymous logging converts silence into data without exposing individuals. Initiate tomorrow.",
  }),
  ("c",
   "A booth notebook... Lord. They'd do that. Nobody has to be the crazy one, it's just the diner's book. Vern, that's sneaky.",
   "A booth notebook... Lord. They'd do that. Nobody has to be the crazy one, it's just, um... it's just the diner's book. Vern, that's sneaky."),
  ("v", {
   "neutral": "It's radio, ma'am - I've heard every kind of quiet there is. Start the book, date every page, and when it's thick enough to thump on a table, you call this line and we'll read the whole town on the air - initials and all. Thanks for calling. Tell the regulars the coffee's on me.",
   "tired": "... it's radio, ma'am. i've heard every kind of quiet there is. start the book. date every page. and when it's thick enough to thump on a table, call this line - we'll read the whole town on the air. initials and all. tell the regulars the coffee's on me.",
   "irritated": "It's radio, ma'am - I've heard every kind of quiet there is. Start the book, date every page, and when it's thick enough to thump on a table, call this line - we'll read the whole town on the air. Initials and all. Tell the regulars the coffee's on me.",
   "gruff": "It's radio, ma'am. Heard every kind of quiet there is. Start the book. Date every page. When it thumps on a table, call me - we'll read the whole town on air. Initials and all. Coffee's on me.",
   "amused": "Ha - it's RADIO, ma'am! I've heard every kind of quiet there is! Start the book, date every page, and when it's thick enough to thump on a table, you call this line and we'll read the whole town on the air - initials and all! Tell the regulars the coffee's on me!",
   "focused": "This is the trade: distributed anonymous logging, dated and preserved. When volume warrants, transmit the log to this program for broadcast reading - initials intact, identities protected. Inform the regulars the coffee is on me. Thank you for calling.",
  }),
 ],
},
{
 "arcId": "ufo_call_grader",
 "legitimacy": "Fake",
 "gender": "male",
 "personality": "charismatic_storyteller",
 "summary": "Longtime listener pitches himself as the show's official caller-grader with scorecards",
 "notes": "Opinion/meta caller - no sighting, all ego (Fake tell: demands airtime for grading others). Vern concedes adjective-watching is real tradecraft, refuses the segment, then flips it: grade live, once, when someone earns it. Comedic",
 "turns": [
  ("v", {
   "neutral": "You're on the air. The screener says you called to grade my other callers.",
   "tired": "... you're on. you called to grade my other callers. alright.",
   "irritated": "You're on. You called to grade the other callers. Really.",
   "gruff": "You're on. Grading callers. Go.",
   "amused": "You're on the air to GRADE the other callers! Six years of listening and this is where it lands! Go on.",
   "focused": "You're on the air. You propose to evaluate other callers. State your methodology.",
  }),
  ("c",
   "Scorecards, Vern! I've been listening six years - I've got a system. Last night's trucker: detail, eight out of ten. Consistency, nine. Believability - ha! - four. Nobody grades your line, so I do. I want a segment. Friday nights. The Caller Report.",
   "Scorecards, Vern! I've been listening six years - I've got a system. Last night's trucker: detail, eight out of ten. Consistency, nine. Believability - ha! - four. Nobody grades your line, so I do. I want a segment, man. Friday nights. The Caller Report, uh... with sound effects."),
  ("v", {
   "neutral": "A segment. Do you realize this is the only show on the dial where the callers grade the host right back?",
   "tired": "... a segment. you realize this is the only show on the dial where the callers grade the host right back?",
   "irritated": "A segment. You realize this is the only show on the dial where callers grade the host back?",
   "gruff": "A segment. Callers grade me back on this dial. You realize that?",
   "amused": "Ha! A SEGMENT! Do you realize this is the only show on the dial where the callers grade the host right back?",
   "focused": "A recurring segment. Note that caller evaluation of the host is already standard on this program.",
  }),
  ("c",
   "Exactly! Democracy of the airwaves! Look - your trucker had the right cadence, but silent triangular object is copy-paste off the internet. Real witnesses say 'it didn't sound like anything.' Fakes use adjectives. I can hear a script by the second sentence. That's a gift, and you're wasting it on - well, on me not having a segment.",
   "Exactly! Democracy of the airwaves! Look - your trucker had the right cadence, but, uh... 'silent triangular object' is copy-paste off the internet. Real witnesses say 'it didn't sound like anything.' Fakes use adjectives, man. I can hear a script by the second sentence. That's a gift, and you're wasting it on - well, on me not having a segment."),
  ("v", {
   "neutral": "Hold on - I'll give you half of that. Adjective-watching is real tradecraft; it's how Hynek's people sorted files, because engineers use nouns and storytellers use adjectives. I've done twenty years of it with the same ear. But here's what your scorecard misses: the trucker you gave a four put his name, his phone, and his job on the line when he called. Your nine-out-of-ten detail came from a man with nothing to lose by lying. A grade is cheap. A name isn't. Fridays are booked.",
   "tired": "... i'll give you half of that. adjective-watching is real - hynek's people sorted files that way. engineers use nouns, storytellers use adjectives. twenty years i've done it with the same ear. but your scorecard misses this: the trucker you gave a four put his name, his phone, and his job on the line when he called. a grade is cheap. a name isn't. fridays are booked.",
   "irritated": "I'll give you half of that. Adjective-watching is real tradecraft - Hynek's people sorted files that way: engineers use nouns, storytellers use adjectives. I've done twenty years of it. But your scorecard misses this: the trucker you gave a four put his name, his phone, and his job on the line. A grade is cheap. A name isn't. Fridays are booked.",
   "gruff": "Half of that's right. Adjective-watching is real - Hynek sorted files that way. Engineers use nouns, storytellers use adjectives. Twenty years, same ear. But your four-out-of-ten trucker put his name, phone, and job on the line. A grade's cheap. A name isn't. Fridays are booked.",
   "amused": "Hold on, hold on - I'll give you HALF of that! Adjective-watching is real tradecraft - it's how Hynek's people sorted files, because engineers use nouns and storytellers use adjectives! Twenty years I've done it with the same ear! But here's what your scorecard misses, my friend: the trucker you gave a FOUR put his name, his phone, and his job on the line when he called! Your nine-out-of-ten detail came from a man with nothing to lose by lying! A grade is cheap - a name isn't! And Fridays are BOOKED!",
   "focused": "Partial concession: adjective analysis is legitimate tradecraft - Hynek's screening separated engineers, who use nouns, from storytellers, who use adjectives. I have applied it for twenty years. Your scoring model, however, omits the risk variable: last night's trucker attached his name, phone number, and employment to the claim. Grades are costless; names are collateral. The Friday slot is committed.",
  }),
  ("c",
   "A name isn't cheap... alright, that's - that's actually a good line. Can I use that? Fine - no segment. But you're leaving points on the table, Vern. The dashcam lady from last month? Ten out of ten and she got four minutes.",
   "A name isn't cheap... alright, that's - that's actually a good line. Can I use that? Fine - no segment. But you're leaving points on the table, Vern. The dashcam lady from last month? Ten out of ten and she got, like... four minutes."),
  ("v", {
   "neutral": "The dashcam lady got four minutes because four minutes was all her story needed - and she got her footage sent to two labs, which is more than your scorecard ever did for anybody. You want to help the show? Keep the ears, drop the numbers. Next time you hear a script read out loud, you call and tell me why - live, once, no repeats. That's the segment.",
   "tired": "... the dashcam lady got four minutes because four minutes was all her story needed - and she got her footage to two labs. that's more than your scorecard ever did for anybody. want to help? keep the ears, drop the numbers. next time you hear a script read out loud, call and tell me why - live, once, no repeats. that's the segment.",
   "irritated": "The dashcam lady got four minutes because that's all her story needed - and her footage went to two labs, which is more than your scorecard ever did for anybody. You want to help? Keep the ears, drop the numbers. Next time you hear a script, call and tell me why - live, once, no repeats. That's the segment.",
   "gruff": "Dashcam lady got four minutes - all her story needed. Her footage went to two labs. More than your scorecard ever did anybody. Want to help? Keep the ears, drop the numbers. Hear a script, call, say why. Live, once, no repeats. That's the segment.",
   "amused": "The dashcam lady got four minutes because four minutes was ALL her story needed - and she got that footage sent to two labs, which is more than your scorecard ever did for anybody! Ha! You want to help the show? Keep the ears, drop the numbers! Next time you hear a script read out loud, you call and tell me why - live, once, no repeats! THAT's the segment!",
   "focused": "The dashcam reporter received four minutes because her account required no more - and her footage was submitted to two laboratories, an outcome your scoring system has never produced. To contribute: retain the analytical ear, discard the numerics. Upon detecting scripted testimony, call and articulate the basis - live, single appearance, no recurring slot. That is the segment.",
  }),
  ("c",
   "Live, once, no repeats... you'd put me on to take apart a caller in real time? Vern, I was born for this. I'm going to start practicing my voice.",
   "Live, once, no repeats... you'd put me on to take apart a caller in real time? Vern, I was born for this. I'm gonna start, uh... practicing my voice."),
  ("v", {
   "neutral": "When they've earned it - and when you remember there's somebody's trucker on the other end of that line at two in the morning. Keep the scorecard at home, bring the ear on air. That's the deal. Thanks for calling - first critic I ever booked.",
   "tired": "... when they've earned it. and when you remember there's somebody's trucker on the other end at two in the morning. scorecard stays home, ear comes on air. that's the deal. first critic i ever booked.",
   "irritated": "When they've earned it - and when you remember there's somebody's trucker on the other end of that line at two in the morning. Scorecard stays home, the ear comes on air. That's the deal. First critic I ever booked.",
   "gruff": "When they've earned it. And remember - somebody's trucker on the other end at two AM. Scorecard stays home. Ear comes on air. That's the deal. First critic I booked.",
   "amused": "When they've EARNED it - and when you remember there's somebody's trucker on the other end of that line at two in the morning! Keep the scorecard at home, bring the ear on air - that's the deal! Thanks for calling: first critic I ever booked!",
   "focused": "Conditional on merit - and on remembering that the opposing line carries a working trucker at 2 AM. The scorecard remains private; the analytical ear goes to air. Agreement recorded. First critic this program has booked. Thank you for calling.",
  }),
 ],
},
]
