namespace KBTV.Dialogue
{
    /// <summary>
    /// Resolves the topic folder an audio line's file lives under.
    /// Voice files (generated by Tools/AudioGeneration/generate_arc_audio.py) are stored
    /// under the topic taken from the line id prefix, which is the single source of truth
    /// shared by the generator and the runtime.
    /// </summary>
    public static class ArcAudioTopics
    {
        /// <summary>
        /// Map an arc line id (e.g. "ufos_fake_topic_switch_ghost_vern_neutral_1") to its
        /// audio topic folder. Falls back to <paramref name="fallback"/> when the id carries
        /// no recognizable topic token.
        /// </summary>
        public static string GetTopicFolder(string lineId, string fallback)
        {
            if (string.IsNullOrEmpty(lineId))
            {
                return fallback;
            }

            return lineId.Split('_')[0].ToLowerInvariant() switch
            {
                "ufo" or "ufos" => "UFOs",
                "ghosts" => "Ghosts",
                "cryptid" or "cryptids" => "Cryptids",
                "conspiracies" => "Conspiracies",
                _ => fallback
            };
        }
    }
}
